
--TABLA MP_localidad, se llena del archivo localidades.csv (faltan las comunas)

COPY "MP_localidad" ("id","nombre","tipo") FROM  '/home/gonzalo/Escritorio/mipega/poblado/localidades.csv'
WITH DELIMITER ';';

COPY "MP_localidad" FROM  '/home/gonzalo/Escritorio/mipega/poblado/localidades2.csv'
WITH DELIMITER ';';

--TABLA MP_nacionalidad, se llena del archivo pais.csv
COPY "MP_nacionalidad" FROM  '/home/gonzalo/Escritorio/mipega/poblado/pais.csv'
WITH DELIMITER ';';

--TABLA MP_institucion, se llena con el archivo instituciones.csv (tiene solouniversidades, faltan institutos, cfts y colegios)

COPY "MP_institucion" FROM  '/home/gonzalo/Escritorio/mipega/poblado/instituciones.csv'
WITH DELIMITER ';';


INSERT INTO "MP_cargo"(
            id, nombre)
    VALUES
(1, 'Abogado '),
(2, 'Abogado especialista '),
(3, 'Abogado especialista sectorial '),
(4, 'Abogado jefe '),
(5, 'Actor '),
(6, 'Administrador '),
(7, 'Administrador de redes y recursos de informatica '),
(8, 'Administrador jefe '),
(9, 'Almacenista (Codigo Transitorio) '),
(10, 'Almacenista jefe '),
(11, 'Analista central de Presupuesto '),
(12, 'Analista de asuntos audiovisuales '),
(13, 'Analista de colocaciÃ³n y seguimiento de pasantias '),
(14, 'Analista de higiene y seguridad industrial '),
(15, 'Analista de informaciÃ³n y control estudiantil '),
(16, 'Analista de informaciÃ³n y control estudiantil jefe '),
(17, 'Analista de laboratorio de protecciÃ³n ambiental '),
(18, 'Analista de nomina '),
(19, 'Analista de organizaciÃ³n y sistemas '),
(20, 'Analista de presupuesto '),
(21, 'Analista de recursos humanos '),
(22, 'Analista de registro y control estadistico '),
(23, 'Analista de registro y control estadistico jefe '),
(339, 'analista de Sistemas'),
(24, 'Analista especialista de recursos humanos '),
(25, 'Analista financiero '),
(340, 'Analista Programador'),
(26, 'Analista programador de sistemas '),
(27, 'Animador cultural '),
(28, 'Archivista '),
(29, 'Archivista jefe '),
(30, 'Arquitecto '),
(31, 'Arreglista musical '),
(32, 'Asesor artistico '),
(41, 'Asiste de botanica '),
(33, 'Asistente administrativo '),
(34, 'Asistente agropecuario '),
(35, 'Asistente de almacen (codigo transitorio) '),
(36, 'Asistente de anatomia y patologia '),
(37, 'Asistente de asuntos audiovisuales '),
(38, 'Asistente de asuntos literarios '),
(39, 'Asistente de biblioteca '),
(40, 'Asistente de biologia '),
(42, 'Asistente de camara '),
(43, 'Asistente de campo '),
(44, 'Asistente de contabilidad '),
(45, 'Asistente de costos de obras '),
(46, 'Asistente de director de orfeon Universitario '),
(47, 'Asistente de entomologÃ­a '),
(48, 'Asistente de especialista en informaciÃ³n '),
(49, 'Asistente de farmacia '),
(50, 'Asistente de hidrometeorologia '),
(51, 'Asistente de histologia '),
(52, 'Asistente de informacion y control estudiantil '),
(53, 'Asistente de investigaciÃ³n en ciencias basicas, naturales y'),
(54, 'Asistente de investigaciÃ³n en ciencias sociales '),
(55, 'Asistente de laboratorio '),
(56, 'Asistente de laboratorio clinico '),
(57, 'Asistente de laboratorio de computaciÃ³n '),
(58, 'Asistente de laboratorio de idiomas '),
(59, 'Asistente de mantenimiento de equipos y redes de informatica'),
(60, 'Asistente de nomina '),
(61, 'Asistente de organizaciÃ³n cultural '),
(62, 'Asistente de preescolar '),
(63, 'Asistente de presupuesto '),
(64, 'Asistente de prevision y desarrollo social '),
(65, 'Asistente de produccion de rediodifusora '),
(66, 'Asistente de protocolo '),
(67, 'Asistente de psicologo (codigo transitorio) '),
(68, 'Asistente de publicaciones '),
(69, 'Asistente de publicidad y mercadeo '),
(70, 'Asistente de recursos humanos '),
(72, 'Asistente de seguros '),
(71, 'Asistente de seguros de transporte automotor '),
(73, 'Asistente de tesoreria '),
(74, 'Asistente de topografÃ­a '),
(75, 'Asistente de veterinaria '),
(76, 'Asistente de zootecnia '),
(77, 'Asistente ejecutivo de egreamigos '),
(78, 'Asistente ejecutivo de estudios para graduados '),
(79, 'Asistente ejecutivo de relaciones interinstitucionales '),
(80, 'Asistente financiero '),
(329, 'Asistente Social'),
(81, 'Atrileo '),
(82, 'Auditor '),
(83, 'Auxiliar de archivo '),
(84, 'Auxiliar de biblioteca '),
(85, 'Auxiliar de laboratorio '),
(86, 'Auxiliar de registro y estadÃ­sticas de servicios asistencia'),
(87, 'Auxiliar de servicios para el arte '),
(88, 'ayudante de taller de artes del fuego '),
(89, 'Bioanalista '),
(90, 'Bombero '),
(91, 'Bombero inspector '),
(92, 'Bombero jefe '),
(93, 'Cajero '),
(94, 'Cajero jefe '),
(95, 'Caligrafo '),
(96, 'Camarografo '),
(97, 'Capellan '),
(98, 'Capitan de buque '),
(99, 'Cartografo '),
(100, 'Citotecnologo '),
(101, 'Comandante del cuerpo de Bomberos '),
(102, 'Comprador '),
(103, 'Comprador jefe '),
(104, 'Concertino '),
(105, 'Consultor de informaciÃ³n y control estudiantil '),
(106, 'Contabilista '),
(107, 'Contador '),
(108, 'Contador jefe '),
(109, 'Coordinador academico '),
(110, 'Coordinador administrativo '),
(112, 'Coordinador de biblioteca '),
(113, 'Coordinador de centros de estudios en artes '),
(114, 'Coordinador de cine club '),
(115, 'Coordinador de deporte '),
(120, 'Coordinador de desarrollo de servicios estudiantil '),
(116, 'Coordinador de pasantias y actividades complementarias '),
(117, 'Coordinador de preescolar '),
(119, 'Coordinador de publicaciones '),
(111, 'Coordinador de suntos literarios '),
(121, 'Coordinador general de deporte '),
(118, 'Coordinador produccion de radiodifusora '),
(122, 'Coordinador sectorial de cultura '),
(123, 'Coralista lider de cuerdas '),
(124, 'Corrector de publicaciones '),
(125, 'Curador '),
(126, 'Diagramador '),
(127, 'Dibujante '),
(128, 'Dibujante ilustrador '),
(129, 'Dibujante ilustrador jefe '),
(130, 'Dibujante jefe '),
(131, 'Dietista '),
(132, 'Director de agrupacion musical '),
(133, 'Director de ballet o danza '),
(134, 'Director de coral '),
(136, 'Director de orquesta '),
(137, 'Director de teatro '),
(138, 'Director de titeres y marionetas '),
(139, 'Director educativo '),
(135, 'Director orfeon universitario '),
(140, 'diseÃ±ador curricular '),
(141, 'DiseÃ±ador grafico '),
(142, 'Docente de artes auditivas '),
(143, 'Docente de artes plasticas '),
(144, 'Docente de aula '),
(145, 'Docente de preescolar '),
(146, 'Docente en artes escenicas '),
(147, 'Documentalista de bienes inmuebles '),
(148, 'Economo '),
(149, 'Editor de Asuntos audiovisuales '),
(150, 'Editor historico '),
(342, 'Ejecutivo de Ventas'),
(151, 'Enfermera (o) '),
(153, 'Enfermera (o) comunitaria '),
(152, 'Enfermera (o) instrumentista '),
(154, 'Enfermera (o) jefe '),
(155, 'Entrenador deportivo '),
(156, 'Especialista de sistemas de informatica '),
(157, 'Especialista en asistencia tecnica institucional '),
(158, 'Especialista en asusntos literarios '),
(159, 'Especialista en informaciÃ³n '),
(160, 'Especialista en informaciÃ³n jefe '),
(161, 'Especialista en mtto de equipos de computaciÃ³n '),
(162, 'Especialista en pasantias y actividades complementarias '),
(163, 'Especialista organizacional '),
(164, 'Evaluador curricular '),
(165, 'Expendedor de material didactico '),
(166, 'Facilitador de desarrollo de recursos humanos '),
(167, 'Facilitador de desarrollo en artes auditivas '),
(168, 'Facilitador de desarrollo en artes escenicas '),
(169, 'Facilitador de desarrollo en artes plasticas '),
(170, 'Facilitador de desarrollo en asuntos literarios '),
(171, 'Farmaceutico '),
(172, 'Fisioterapeuta '),
(173, 'Fotografo '),
(174, 'Fotolitografo '),
(175, 'Gerente de promocion y administraciÃ³n de espacios y patrimo'),
(325, 'gerente general'),
(176, 'Higienista dental '),
(177, 'Ingeniero agronomo '),
(178, 'Ingeniero agronomo jefe '),
(179, 'Ingeniero de proyectos '),
(180, 'Ingeniero forestal '),
(181, 'Inspector de control de perdidas '),
(182, 'Inspector de higiene y control de precios de alimentos '),
(183, 'Inspector de obras '),
(184, 'Inspector de proteccion ambiental '),
(185, 'Inspector de seguridad industrial e higiene ocupacional '),
(186, 'Inspector general de los servicios bomberiles '),
(187, 'Instructor de desarrollo en artes auditivas '),
(188, 'Instructor de desarrollo en artes escenicas '),
(189, 'Instructor de desarrollo en artes plasticas '),
(190, 'Instrumentista academico '),
(191, 'Instrumentista academico lider de cuerdas '),
(192, 'Instrumentista folklorico '),
(193, 'Interprete vocal '),
(194, 'Investigador en ciencias basicas, naturales y aplicadas '),
(195, 'Investigador en ciencias sociales '),
(196, 'Investigador ocupacional '),
(335, 'ITO'),
(197, 'Jefe central de informacion y control estudiantil '),
(198, 'Jefe central de presupuesto '),
(199, 'Jefe central de recursos humanos '),
(200, 'Jefe de analisi y control financiero '),
(201, 'Jefe de analisis y procesamiento de compras '),
(202, 'Jefe de artes '),
(203, 'Jefe de asesoramiento, apoyo y orientaciÃ³n '),
(204, 'Jefe de asistencia socio-econÃ³mica estudiantil '),
(205, 'Jefe de contabilidad '),
(206, 'Jefe de control previo y/o posterior '),
(207, 'Jefe de correo '),
(208, 'Jefe de emision de pagos '),
(209, 'Jefe de fotografÃ­a '),
(210, 'Jefe de informaciÃ³n y control estudiantil '),
(211, 'Jefe de informatica '),
(212, 'Jefe de inventarios '),
(331, 'Jefe de local'),
(213, 'Jefe de mantenimiento y reparaciones '),
(214, 'Jefe de nomina '),
(215, 'Jefe de obras '),
(216, 'Jefe de operaciones bomberiles '),
(217, 'Jefe de organizaciÃ³n y sistemas '),
(218, 'Jefe de planes operativos y estratÃ©gicos '),
(219, 'Jefe de prensa '),
(220, 'Jefe de prevenciÃ³n, investigaciÃ³n e inspecciÃ³n de incendi'),
(221, 'Jefe de producciÃ³n de audiovisuales '),
(222, 'Jefe de protecciÃ³n ambiental '),
(223, 'Jefe de proteccion y seguridad '),
(224, 'Jefe de protocolo '),
(225, 'Jefe de proyectista arquitectonicos y de ingenierÃ­a '),
(343, 'Jefe de Proyecto Informático'),
(226, 'Jefe de recursos humanos '),
(227, 'Jefe de relaciones interinstitucionales '),
(228, 'Jefe de relaciones publicas '),
(229, 'Jefe de salud integral '),
(230, 'Jefe de seccion de informatica '),
(231, 'Jefe de seguridad industrial e higiene ocupacional '),
(232, 'Jefe de seguros '),
(233, 'Jefe de servicios generales '),
(234, 'Jefe de taller automotriz '),
(235, 'Jefe de taller metalmecanico '),
(236, 'Jefe de talleres de obras '),
(237, 'Jefe de tesoreria '),
(238, 'Jefe de trafico '),
(239, 'Jefe de unidades nutricionales '),
(240, 'Jefe sectorial de compras '),
(241, 'Jefe sectorial de Presupuesto '),
(242, 'Kinesiologo '),
(243, 'Locutor '),
(244, 'Luminotecnico '),
(245, 'Maquetista '),
(246, 'Maquinista de buque '),
(247, 'Mecanico dental '),
(248, 'Medico jefe '),
(249, 'Medico veterinario '),
(250, 'Microfilmador '),
(337, 'Músico'),
(338, 'Músico Guitarrista'),
(251, 'Odontologo '),
(252, 'Oficial de correo '),
(334, 'Oficina Técnica'),
(253, 'Oficinista '),
(254, 'Operador de audio '),
(255, 'Operador de computacion '),
(256, 'Operador de equipos de telecomunicaciones '),
(257, 'Operador de maquina de reproducciÃ³n (codigo transitorio) '),
(330, 'Operador de Retroexcavadora'),
(258, 'Orientador '),
(259, 'Periodista '),
(260, 'Planificador '),
(261, 'Planificador central '),
(262, 'Planificador de informaciÃ³n y control estudiantil '),
(328, 'Profesor'),
(327, 'Profesor de Historia'),
(263, 'Programador de sistemas '),
(336, 'Programador Perl'),
(341, 'Programador Senior'),
(264, 'Promotor cultural '),
(265, 'Promotor de cursos '),
(266, 'Promotor de relaciones publicas e interinstitucionales '),
(267, 'Promotor social '),
(268, 'Promotor vendedor de material didactico '),
(333, 'Propuesta'),
(269, 'Psicologo '),
(270, 'Psicologo jefe '),
(271, 'psicopedagogo '),
(272, 'Recepcionista '),
(273, 'Registrador de bienes '),
(274, 'Revisor de contraloria '),
(326, 'secretaria '),
(275, 'Secretaria (o) '),
(276, 'Secretaria (o) bilingÃ¼e '),
(277, 'Secretaria (o) ejecutiva (o) '),
(278, 'Secretaria (o) ejecutiva (o) bilingÃ¼e '),
(279, 'Serigrafista '),
(280, 'Serigrafista principal '),
(281, 'Soplador de vidrio '),
(282, 'Soplador de vidrio jefe '),
(283, 'Sub-director educativo '),
(284, 'Supervisor de asuntos audiovisuales '),
(285, 'Supervisor de biblioteca '),
(286, 'Supervisor de carpinterÃ­a (codigo transitorio) '),
(287, 'Supervisor de costos de obras '),
(288, 'Supervisor de laboratorio '),
(289, 'Supervisor de operaciones de radiodifusora '),
(290, 'Supervisor de Pintores (codigo transitorio) '),
(299, 'Supervisor de programa asistencia medica estudiantil '),
(291, 'Supervisor de protecciÃ³n y seguridad '),
(292, 'Supervisor de registro y apoyo asistencial '),
(293, 'Supervisor de registro y control de bienes '),
(294, 'Supervisor de servicios (codigo transitorio) '),
(295, 'Supervisor de servicios de mantenimiento '),
(296, 'Supervisor de servicios generales '),
(297, 'Supervisor de taller de publicaciones '),
(298, 'Supervisor de transporte '),
(332, 'Supervisor.'),
(300, 'Tallador de diamantes '),
(301, 'Taquillero (codigo transitorio) '),
(302, 'Taxidermista '),
(303, 'Tecnico acuicultor '),
(304, 'Tecnico agropecuario '),
(305, 'Tecnico de electromedicina '),
(306, 'Tecnico de equipos de telecomunicaciones '),
(307, 'Tecnico de geologia y minas '),
(308, 'Tecnico de grabacion de radiodifusora '),
(309, 'Tecnico de petroleo '),
(310, 'Tecnico de taller de micromecanica '),
(311, 'Tecnico de telematica '),
(312, 'Tecnico electricista '),
(313, 'Tecnico electromecÃ¡nico '),
(314, 'Tecnico electromecÃ¡nico de equipos odontolÃ³gicos '),
(315, 'Tecnico forestal '),
(316, 'Tecnico plomero (codigo transitorio) '),
(317, 'Tecnico quimico '),
(318, 'Tecnico radiologo '),
(319, 'Telefonista '),
(320, 'Topografo '),
(321, 'Trabajador social '),
(322, 'Trabajador social jefe '),
(323, 'Traductor '),
(324, 'Zootecnista ');



--titulos--
INSERT INTO "MP_titulo"(
            id, nombre, tipo)
    VALUES
(1, 'ActuaciÃ³n Teatral ', 'p'),
(2, 'BiologÃ­a con menciones ', 'p'),
(3, 'DirecciÃ³n Audiovisual ', 'p'),
(4, 'EducaciÃ³n de PÃ¡rvulos ', 'p'),
(5, 'IngenierÃ­a Civil con Diploma de Especialidad ', 'p'),
(6, 'IngenierÃ­a Civil de Industrias ', 'p'),
(7, 'IngenierÃ­a Civil en BiotecnologÃ­a ', 'p'),
(8, 'IngenierÃ­a Civil en ComputaciÃ³n ', 'p'),
(9, 'IngenierÃ­a Civil en Electricidad ', 'p'),
(10, 'IngenierÃ­a Comercial con menciones ', 'p'),
(11, 'Ingeniero AgrÃ³nomo ', 'p'),
(12, 'Ingeniero Forestal ', 'p'),
(13, 'Licenciatura en Artes y Humanidades ', 'p'),
(14, 'Licenciatura en AstronomÃ­a ', 'p'),
(15, 'Licenciatura en Ciencias Sociales ', 'p'),
(16, 'Licenciatura en EstÃ©tica ', 'p'),
(17, 'Licenciatura en FÃ­sica ', 'p'),
(18, 'SociologÃ­a ', 'p'),
(19, 'Arquitectura ', 'p'),
(20, 'BiologÃ­a ', 'p'),
(21, 'Ciencias Religiosas ', 'p'),
(22, 'GeÃ³grafo ', 'p'),
(23, 'IngenierÃ­a Civil BioquÃ­mica ', 'p'),
(24, 'IngenierÃ­a Civil en Metalurgia Extractiva ', 'p'),
(25, 'IngenierÃ­a de Alimentos ', 'p'),
(26, 'IngenierÃ­a de EjecuciÃ³n en Bioprocesos ', 'p'),
(27, 'IngenierÃ­a de EjecuciÃ³n en InformÃ¡tica ', 'p'),
(28, 'IngenierÃ­a de Transporte ', 'p'),
(29, 'IngenierÃ­a ElÃ©ctrica ', 'p'),
(30, 'IngenierÃ­a ElectrÃ³nica ', 'p'),
(31, 'IngenierÃ­a MecÃ¡nica ', 'p'),
(32, 'IngenierÃ­a Pesquera ', 'p'),
(33, 'InterpretaciÃ³n InglÃ©s EspaÃ±ol ', 'p'),
(34, 'IntÃ©rprete Musical ', 'p'),
(35, 'Licenciatura en Arte ', 'p'),
(36, 'OceanografÃ­a ', 'p'),
(37, 'Ã“ptica ', 'p'),
(38, 'PedagogÃ­a en BiologÃ­a y Ciencias Naturales ', 'p'),
(39, 'PedagogÃ­a en FÃ­sica y/o Licenciatura en FÃ­sica ', 'p'),
(40, 'PedagogÃ­a en MatemÃ¡ticas y/o Licenciatura en ', 'p'),
(41, 'PedagogÃ­a en MÃºsica y/o Licenciatura en Ciencias ', 'p'),
(42, 'PedagogÃ­a en ReligiÃ³n y Moral y/o Bachillerato ', 'p'),
(43, 'QuÃ­mica Industrial ', 'p'),
(44, 'IngenierÃ­a Civil en ComputaciÃ³n e InformÃ¡tica ', 'p'),
(45, 'IngenierÃ­a de EjecuciÃ³n AgrÃ­cola BiologÃ­a Maritima ', 'p'),
(46, 'IngenierÃ­a de EjecuciÃ³n en Pesca y Acuicultura ', 'p'),
(47, 'IngenierÃ­a en InformaciÃ³n y Control de GestiÃ³n ', 'p'),
(48, 'IngenierÃ­a en InformÃ¡tica ', 'p'),
(49, 'PedagogÃ­a en BiologÃ­a y QuÃ­mica ', 'p'),
(50, 'PedagogÃ­a en MatemÃ¡tica y FÃ­sica ', 'p'),
(51, 'QuÃ­mica y Farmacia ', 'p'),
(52, 'TraducciÃ³n InglÃ©s-EspaÃ±ol-InglÃ©s ', 'p'),
(53, 'AdministraciÃ³n de Empresas de Turismo ', 'p'),
(54, 'IngenierÃ­a Civil AcÃºstica ', 'p'),
(55, 'IngenierÃ­a en ComputaciÃ³n ', 'p'),
(56, 'IngenierÃ­a en ConservaciÃ³n de Recursos Naturales ', 'p'),
(57, 'IngenierÃ­a Naval ', 'p'),
(58, 'Medicina Veterinaria ', 'p'),
(59, 'PedagogÃ­a en Lenguaje y ComunicaciÃ³n ', 'p'),
(60, 'PsicologÃ­a ', 'p'),
(61, 'Terapia Educacional ', 'p'),
(62, 'IngenierÃ­a en Acuicultura y Pesca ', 'p'),
(63, 'IngenierÃ­a MarÃ­timo Portuaria ', 'p'),
(64, 'Licenciatura en Ciencias Religiosas ', 'p'),
(65, 'AdministraciÃ³n y AuditorÃ­a ', 'p'),
(66, 'EnfermerÃ­a ', 'p'),
(67, 'IngenierÃ­a Forestal ', 'p'),
(68, 'PedagogÃ­a en EducaciÃ³n Especial ', 'p'),
(69, 'PedagogÃ­a en ReligiÃ³n y FilosofÃ­a ', 'p'),
(70, 'Analista QuÃ­mico ', 'p'),
(71, 'Bachillerato en Ciencias de la Salud ', 'p'),
(72, 'ConstrucciÃ³n Civil ', 'p'),
(73, 'EstadÃ­stica ', 'p'),
(74, 'GeologÃ­a ', 'p'),
(75, 'IngenierÃ­a Civil MetalÃºrgica ', 'p'),
(76, 'IngenierÃ­a de EjecuciÃ³n en ComputaciÃ³n e Informatica ', 'p'),
(77, 'IngenierÃ­a de EjecuciÃ³n en Metalurgia ', 'p'),
(78, 'IngenierÃ­a de EjecuciÃ³n en Procesos QuÃ­micos ', 'p'),
(79, 'Licenciatura en MatemÃ¡ticas ', 'p'),
(80, 'Licenciatura FÃ­sica menciÃ³n AstronomÃ­a ', 'p'),
(81, 'QuÃ­mico MenciÃ³n Metalurgia Extractiva ', 'p'),
(82, 'QuÃ­mico MenciÃ³n Quimica Ambiental ', 'p'),
(83, 'BiÃ³logo en GestiÃ³n de Recursos Naturales ', 'p'),
(84, 'DiseÃ±o de producto ', 'p'),
(85, 'IngenierÃ­a Civil Ambiental ', 'p'),
(86, 'IngenierÃ­a en Acuicultura ', 'p'),
(87, 'Licenciatura en AntropologÃ­a ', 'p'),
(88, 'Licenciatura en Artes Visuales ', 'p'),
(89, 'PedagogÃ­a EducaciÃ³n Media en MatemÃ¡ticas ', 'p'),
(90, 'TÃ©cnico Universitario en Acuicultura ', 'p'),
(91, 'TÃ©cnico Universitario en ProducciÃ³n Agropecuaria ', 'p'),
(92, 'TraducciÃ³n InglÃ©s - EspaÃ±ol ', 'p'),
(93, 'DiseÃ±o GrÃ¡fico Publicitario ', 'p'),
(94, 'EcologÃ­a Marina ', 'p'),
(95, 'IngenierÃ­a Civil en GeomÃ¡tica ', 'p'),
(96, 'IngenierÃ­a Civil Industrial Electricidad ', 'p'),
(97, 'IngenierÃ­a Civil Industrial ElectrÃ³nica ', 'p'),
(98, 'IngenierÃ­a Civil Industrial MecÃ¡nica ', 'p'),
(99, 'IngenierÃ­a Civil Industrial Minas ', 'p'),
(100, 'IngenierÃ­a Civil Industrial QuÃ­mica ', 'p'),
(101, 'IngenierÃ­a de EjecuciÃ³n Electricidad ', 'p'),
(102, 'IngenierÃ­a de EjecuciÃ³n ElectrÃ³nica ', 'p'),
(103, 'IngenierÃ­a de EjecuciÃ³n en Geomensura ', 'p'),
(104, 'IngenierÃ­a de EjecuciÃ³n en Minas ', 'p'),
(105, 'Licenciatura en Ciencias BiolÃ³gicas ', 'p'),
(106, 'PedagogÃ­a en Ed. FÃ­sica ', 'p'),
(107, 'QuÃ­mica ', 'p'),
(108, 'Servicio Social ', 'p'),
(109, 'IngenierÃ­a Civil en ElectrÃ³nica ', 'p'),
(110, 'IngenierÃ­aCivil en MecÃ¡nica ', 'p'),
(111, 'IngenierÃ­a Civil en Metalurgia ', 'p'),
(112, 'IngenierÃ­a Civil en Minas ', 'p'),
(113, 'IngenierÃ­a Civil InformÃ¡tica y ComputaciÃ³n ', 'p'),
(114, 'IngenierÃ­a de EjecuciÃ³n en Industrias ', 'p'),
(115, 'PedagogÃ­a en EducaciÃ³n General BÃ¡sica ', 'p'),
(116, 'TecnÃ³logo en AdministraciÃ³n de Empresas ', 'p'),
(117, 'TecnÃ³logo en ConstrucciÃ³n Civil ', 'p'),
(118, 'TecnÃ³logo en Electricidad ', 'p'),
(119, 'TecnÃ³logo en InformÃ¡tica ', 'p'),
(120, 'TecnÃ³logo en InstrumentaciÃ³n y AutomatizaciÃ³n ', 'p'),
(121, 'TecnÃ³logo en Mantenimiento MecÃ¡nico ', 'p'),
(122, 'TecnÃ³logo en Metalurgia ', 'p'),
(123, 'Artes PlÃ¡sticas ', 'p'),
(124, 'Bachillerato ', 'p'),
(125, 'BiologÃ­a Ambiental ', 'p'),
(126, 'BioquÃ­mica ', 'p'),
(127, 'Cine y TelevisiÃ³n ', 'p'),
(128, 'DiseÃ±o Teatral ', 'p'),
(129, 'EducaciÃ³n Parvularia y BÃ¡sica Inicial ', 'p'),
(130, 'IngenierÃ­a Civil con menciÃ³n en Estructuras ', 'p'),
(131, 'IngenierÃ­a Civil de Minas ', 'p'),
(132, 'IngenierÃ­a Civil Electricista ', 'p'),
(133, 'IngenierÃ­a Civil en Materiales ', 'p'),
(134, 'IngenierÃ­a Civil MecÃ¡nica ', 'p'),
(135, 'IngenierÃ­a Civil QuÃ­mica ', 'p'),
(136, 'IngenierÃ­a de la Madera ', 'p'),
(137, 'IngenierÃ­a en BiotecnologÃ­a Molecular ', 'p'),
(138, 'IngenierÃ­a en Recursos Naturales Renovables ', 'p'),
(139, 'InterpretaciÃ³n Musical ', 'p'),
(140, 'Licenciatura en Ciencias, menciÃ³n AstronomÃ­a ', 'p'),
(141, 'Licenciatura en Ciencias, menciÃ³n FÃ­sica ', 'p'),
(142, 'Licenciatura en Ciencias MenciÃ³n GeofÃ­sica ', 'p'),
(143, 'Licenciatura en Historia ', 'p'),
(144, 'Licenciatura en Lengua y Literatura Inglesas ', 'p'),
(145, 'QuÃ­mica Ambiental ', 'p'),
(146, 'Sonido ', 'p'),
(147, 'TeorÃ­a de la MÃºsica ', 'p'),
(148, 'TeorÃ­a e Historia del Arte ', 'p'),
(149, 'Artes Visuales ', 'p'),
(150, 'AstronomÃ­a ', 'p'),
(151, 'AuditorÃ­a ', 'p'),
(152, 'BioingenierÃ­a ', 'p'),
(153, 'Ciencias FÃ­sicas y AstronÃ³micas ', 'p'),
(154, 'Ciencias PolÃ­ticas y Administrativas ', 'p'),
(155, 'Derecho ', 'p'),
(156, 'EducaciÃ³n Diferencial ', 'p'),
(157, 'GeofÃ­sica ', 'p'),
(158, 'GeografÃ­a ', 'p'),
(159, 'IngenierÃ­a Agroindustrial ', 'p'),
(160, 'IngenierÃ­a Ambiental ', 'p'),
(161, 'IngenierÃ­a Civil Aeroespacial ', 'p'),
(162, 'IngenierÃ­a Civil AgrÃ­cola ', 'p'),
(163, 'IngenierÃ­a Civil de Materiales ', 'p'),
(164, 'IngenierÃ­a Civil en Telecomunicaciones ', 'p'),
(165, 'IngenierÃ­a Civil Primer AÃ±o ComÃºn ', 'p'),
(166, 'IngenierÃ­a de EjecuciÃ³n Forestal ', 'p'),
(167, 'IngenierÃ­a en BiotecnologÃ­a Marina y Acuicultura ', 'p'),
(168, 'IngenierÃ­a en BiotecnologÃ­a Vegetal ', 'p'),
(169, 'IngenierÃ­a EstadÃ­stica ', 'p'),
(170, 'IngenierÃ­a GeomÃ¡tica ', 'p'),
(171, 'KinesiologÃ­a ', 'p'),
(172, 'Licenciatura en QuÃ­mica QuÃ­mico ', 'p'),
(173, 'PedagogÃ­a ', 'p'),
(174, 'PedagogÃ­a en Ciencias Naturales y BiologÃ­a ', 'p'),
(175, 'QuÃ­mico Analista ', 'p'),
(176, 'Contador PÃºblico y Auditor ', 'p'),
(177, 'IngenierÃ­a Civil Industrial m. Bioprocesos ', 'p'),
(178, 'IngenierÃ­a Civil Industrial m. InformÃ¡tica ', 'p'),
(179, 'IngenierÃ­a Civil MatemÃ¡tica ', 'p'),
(180, 'IngenierÃ­a Civil TelemÃ¡tica ', 'p'),
(181, 'IngenierÃ­a en Recursos Naturales ', 'p'),
(182, 'Licenciatura en FÃ­sica Aplicada ', 'p'),
(183, 'PedagogÃ­a en Castellano y ComunicaciÃ³n ', 'p'),
(184, 'PedagogÃ­a en EucaciÃ³n FÃ­sica, Deportes y Recreacion ', 'p'),
(185, 'PedagogÃ­a en Historia, GeografÃ­a y EducaciÃ³n ', 'p'),
(186, 'PedagogÃ­a MatemÃ¡tica ', 'p'),
(187, 'AgronomÃ­a ', 'p'),
(188, 'AntropologÃ­a ', 'p'),
(189, 'EducaciÃ³n Parvularia y PsicopedagogÃ­a ', 'p'),
(190, 'Historiador ', 'p'),
(191, 'Historia y GeografÃ­a Ingreso ComÃºn Conducente ', 'p'),
(192, 'IngenierÃ­a Civil ComputaciÃ³n e InformÃ¡tica ', 'p'),
(193, 'IngenierÃ­a Civil y EjecuciÃ³n Ingreso ComÃºn ', 'p'),
(194, 'IngenierÃ­a de EjecuciÃ³n en IngenierÃ­a Industrial ', 'p'),
(195, 'IngenierÃ­a de EjecuciÃ³n MecÃ¡nica ', 'p'),
(196, 'IngenierÃ­a EjecuciÃ³n ElÃ©ctrica ', 'p'),
(197, 'IngenierÃ­a EjecuciÃ³n ElectrÃ³nica ', 'p'),
(198, 'IngenierÃ­a EjecuciÃ³n en ComputaciÃ³n e InformÃ¡tica ', 'p'),
(199, 'IngenierÃ­a EjecuciÃ³n en Redes Computacionales ', 'p'),
(200, 'IngenierÃ­a en Redes Computacionales ', 'p'),
(201, 'IngenierÃ­a en Sistemas de Informacion Informatica ', 'p'),
(202, 'IngenierÃ­a MatemÃ¡tico ', 'p'),
(203, 'IngenierÃ­a MecatrÃ³nica ', 'p'),
(204, 'IngenierÃ­a QuÃ­mica Ambiental ', 'p'),
(205, 'KinesiologÃ­a y RehabilitaciÃ³n ', 'p'),
(206, 'Licenciatura en InglÃ©s ', 'p'),
(207, 'Obstetricia y Puericultura menciÃ³n gestiÃ³n ', 'p'),
(208, 'PedagogÃ­a en MatemÃ¡tica y ComputaciÃ³n ', 'p'),
(209, 'Pedagogia en QuÃ­mica y Ciencias Naturales ', 'p'),
(210, 'Profesor de EducaciÃ³n FÃ­sica ', 'p'),
(211, 'QuÃ­mico ', 'p'),
(212, 'Quimico Laboratorista ', 'p'),
(213, 'TecnologÃ­a MÃ©dica/ OftalmologÃ­a ', 'p'),
(214, 'Traductor InglÃ©s-Castellano ', 'p'),
(215, 'AdministraciÃ³n de Negocios Internacionales ', 'p'),
(216, 'AdministraciÃ³n de Recursos GastronÃ³micos ', 'p'),
(217, 'GestiÃ³n en Turismo y Cultura ', 'p'),
(218, 'IngenierÃ­a BiomÃ©dica ', 'p'),
(219, 'IngenierÃ­a Civil ', 'p'),
(220, 'Ingenieria Civil en InformÃ¡tica ', 'p'),
(221, 'IngenierÃ­a Civil OceÃ¡nica ', 'p'),
(222, 'IngenierÃ­a en EstadÃ­stica ', 'p'),
(223, 'Licenciatura en Ciencias Socio- EconÃ³micas ', 'p'),
(224, 'Licenciatura en FÃ­sica menciÃ³n AstronomÃ­a ', 'p'),
(225, 'MatemÃ¡tica ', 'p'),
(226, 'MeteorologÃ­a ', 'p'),
(227, 'Obstetricia y Puericultura ', 'p'),
(228, 'PedagogÃ­a en BiologÃ­a y AstronomÃ­a ', 'p'),
(229, 'PedagogÃ­a en BiologÃ­a y EducaciÃ³n TecnolÃ³gica ', 'p'),
(230, 'PedagogÃ­a en BiologÃ­a y EstadÃ­stica ', 'p'),
(231, 'PedagogÃ­a en FÃ­sica y AstronomÃ­a ', 'p'),
(232, 'PedagogÃ­a en FÃ­sica y EstadÃ­stica Educacionales ', 'p'),
(233, 'Licenciatura en EducaciÃ³n en MatemÃ¡tica ', 'p'),
(234, 'PedagogÃ­a en MatemÃ¡tica y Ciencias Naturales ', 'p'),
(235, 'PedagogÃ­a en MatemÃ¡tica y AstronomÃ­a ', 'p'),
(236, 'PedagogÃ­a en QuÃ­mica y AstronomÃ­a ', 'p'),
(237, 'PedagogÃ­a en QuÃ­mica y EducaciÃ³n TecnolÃ³gica ', 'p'),
(238, 'PedagogÃ­a en QuÃ­mica e InformÃ¡tica Educativa ', 'p'),
(239, 'PedagogÃ­a en QuÃ­mica y EstadÃ­stica Educactiva ', 'p'),
(240, 'Licenciatura en KinesiologÃ­a MenciÃ³n Estudio ', 'p'),
(241, 'IngenierÃ­a Civil ElÃ©ctrica ', 'p'),
(242, 'IngenierÃ­a Civil: ElectrÃ³nica ', 'p'),
(243, 'IngenierÃ­a de EjecuciÃ³n en PrevenciÃ³n de Riesgo ', 'p'),
(244, 'IngenierÃ­a de EjecuciÃ³n QuÃ­mica ', 'p'),
(245, 'IngenierÃ­a en AviaciÃ³n Comercial ', 'p'),
(246, 'IngenierÃ­a en DiseÃ±o de Productos ', 'p'),
(247, 'IngenierÃ­a MecÃ¡nica Industrial ', 'p'),
(248, 'Piloto Comercial ', 'p'),
(249, 'TÃ©cnico Universitario Dibujante Proyectista ', 'p'),
(250, 'TÃ©cnico Universitario en ConstrucciÃ³n Civil ', 'p'),
(251, 'TÃ©cnico Universitario en Control de Alimentos ', 'p'),
(252, 'TÃ©cnico Universitario en Electricidad ', 'p'),
(253, 'TÃ©cnico Universitario en Industrias Madereras ', 'p'),
(254, 'TÃ©cnico Universitario en MecÃ¡nica Automotriz ', 'p'),
(255, 'TÃ©cnico Universitario en MecÃ¡nica Industrial ', 'p'),
(256, 'TÃ©cnico Universitario en PrevenciÃ³n de Riesgo ', 'p'),
(257, 'TÃ©cnico Universitario en Proyectos de Ingenieria ', 'p'),
(258, 'TÃ©cnico Universitario en QuÃ­mica AnalÃ­tica ', 'p'),
(259, 'TÃ©cnico Universitario en QuÃ­mica Industrial ', 'p'),
(260, 'TÃ©cnico Universitario en Sistemas ElectrÃ³nico ', 'p'),
(261, 'Bachillerato en Ciencias de la IngenierÃ­a ', 'p'),
(262, 'BibliotecologÃ­a y DocumentaciÃ³n ', 'p'),
(263, 'CartografÃ­a ', 'p'),
(264, 'Dibujante Proyectista ', 'p'),
(265, 'DiseÃ±o en ComunicaciÃ³n Visual ', 'p'),
(266, 'Ingenieria Civil Industrial menciÃ³n Agroindus ', 'p'),
(267, 'IngenierÃ­a civil Industrial menciÃ³n Sistema de informacion ', 'p'),
(268, 'IngenierÃ­a en AdministraciÃ³n Agroindustrial ', 'p'),
(269, 'IngenierÃ­a en Geomensura ', 'p'),
(270, 'IngenierÃ­a en GestiÃ³n TurÃ­stica ', 'p'),
(271, 'IngenierÃ­a en Industria Alimentaria ', 'p'),
(272, 'IngenierÃ­a en Industria de la Madera ', 'p'),
(273, 'IngenierÃ­a en MecÃ¡nica ', 'p'),
(274, 'IngenierÃ­a en QuÃ­mica ', 'p'),
(275, 'IngenierÃ­a en Transporte y TrÃ¡nsito ', 'p'),
(276, 'IngenierÃ­a de EjecuciÃ³n en GestiÃ³n Ambiental ', 'p'),
(277, 'IngenierÃ­a en EjecuciÃ³n en GestiÃ³n PÃºblica ', 'p'),
(278, 'MÃºsica ', 'p'),
(279, 'PedagogÃ­a en Lengua Castellana y ComunicaciÃ³n ', 'p'),
(280, 'Teatro ', 'p'),
(281, 'Literatura ', 'p'),
(282, 'IngenierÃ­a Civil Agroindustrial ', 'p'),
(283, 'IngenierÃ­a Civil InformÃ¡tica ', 'p'),
(284, 'IngenierÃ­a en AdministraciÃ³n de Empresas ', 'p'),
(285, 'IngenierÃ­a en Agroindustria ', 'p'),
(286, 'IngenierÃ­a en ElectrÃ³nica y Telecomunicaciones ', 'p'),
(287, 'IngenierÃ­a en ProducciÃ³n AgrÃ­cola ', 'p'),
(288, 'Licenciatura en TeologÃ­a ', 'p'),
(289, 'PedagogÃ­a en EducaciÃ³n FÃ­sica ', 'p'),
(290, 'PedagogÃ­a en EducaciÃ³n Parvularia ', 'p'),
(291, 'PedagogÃ­a en EducaciÃ³n Religiosa ', 'p'),
(292, 'PedagogÃ­a en InglÃ©s ', 'p'),
(293, 'PedagogÃ­a en Lengua Castellana ', 'p'),
(294, 'PedagogÃ­a en MÃºsica ', 'p'),
(295, 'TÃ©cnico Superior en AdministraciÃ³n de Empresa ', 'p'),
(296, 'TÃ©cnico Superior en Alimentos ', 'p'),
(297, 'TÃ©cnico Superior en AnÃ¡lisis de Sistemas ', 'p'),
(298, 'TÃ©cnico Superior en Contabilidad ', 'p'),
(299, 'TÃ©cnico Superior en ElectrÃ³nica ', 'p'),
(300, 'TÃ©cnico Superior en EnfermerÃ­a ', 'p'),
(301, 'Bachillerato en MÃºsica ', 'p'),
(302, 'Ciencia PolÃ­tica y Relaciones Internacionales ', 'p'),
(303, 'IngenierÃ­a Comercial ', 'p'),
(304, 'IngenierÃ­a Comercial para Profesionales ', 'p'),
(305, 'Licenciatura en FilosofÃ­a ', 'p'),
(306, 'Licenciatura en Lengua y Literatura ', 'p'),
(307, 'Licenciatura en Trabajo Social ', 'p'),
(308, 'PedagogÃ­a para Profesionales ', 'p'),
(309, 'IngenierÃ­a en EjecuciÃ³n en AdministraciÃ³n de empresas ', 'p'),
(310, 'IngenierÃ­a InformÃ¡tica ', 'p'),
(311, 'PedagogÃ­a y Licenciatura en Artes ', 'p'),
(312, 'Publicidad y ComunicaciÃ³n Integral ', 'p'),
(313, 'TÃ©cnico Universitario en AdministraciÃ³n ', 'p'),
(314, 'TÃ©cnico Universitario en Relaciones PÃºblicas ', 'p'),
(315, 'IngenierÃ­a de EjecuciÃ³n en CartografÃ­a ', 'p'),
(316, 'Relaciones PÃºblicas ', 'p'),
(317, 'AdministraciÃ³n menciÃ³n Agronegocios ', 'p'),
(318, 'CoreografÃ­a y PedagogÃ­a en Danza - Teatro ', 'p'),
(319, 'IngenierÃ­a en EjecuciÃ³n en AdministraciÃ³n de empresas ', 'p'),
(320, 'Licenciatura en Historia Social ', 'p'),
(321, 'PedagogÃ­a en EducaciÃ³n BÃ¡sica menciÃ³n InglÃ©s ', 'p'),
(322, 'PedagogÃ­a en EducaciÃ³n Inicial ', 'p'),
(323, 'PedagogÃ­a en EducaciÃ³n Media menciÃ³n InglÃ©s ', 'p'),
(324, 'PedagogÃ­a en EducaciÃ³n Musical ', 'p'),
(325, 'TÃ©cnico en AdministraciÃ³n de Empresas ', 'p'),
(326, 'TÃ©cnico en GestiÃ³n Industrial ', 'p'),
(327, 'TÃ©cnico en PrevenciÃ³n de Riesgos ', 'p'),
(328, 'EducaciÃ³n Parvularia ', 'p'),
(329, 'IngenierÃ­a en AdministraciÃ³n ', 'p'),
(330, 'PedagogÃ­a en EducaciÃ³n BÃ¡sica ', 'p'),
(331, 'PedagogÃ­a en EducaciÃ³n Diferencial ', 'p'),
(332, 'TÃ©cnico Universitario en EducaciÃ³n Social ', 'p'),
(333, 'Arquitectura del Paisaje ', 'p'),
(334, 'Contabilidad y Auditoria ', 'p'),
(335, 'IngenierÃ­a en Agronegocios ', 'p'),
(336, 'IngenierÃ­a en EjecuciÃ³n en AdministraciÃ³n ', 'p'),
(337, 'PedagogÃ­a en BiologÃ­a y Ciencias ', 'p'),
(338, 'PedagogÃ­a en Lengua y Cultura Inglesas ', 'p'),
(339, 'EducaciÃ³n BÃ¡sica en InglÃ©s ', 'p'),
(340, 'TraducciÃ³n InglÃ©s-EspaÃ±ol ', 'p'),
(341, 'AdministraciÃ³n PÃºblica ', 'p'),
(342, 'Analista Programador ', 'p'),
(343, 'Dramaturgia ', 'p'),
(344, 'FonoaudiologÃ­a ', 'p'),
(345, 'IngenierÃ­a de EjecuciÃ³n en PlanificaciÃ³n ', 'p'),
(346, 'IngenierÃ­a de EjecuciÃ³n Industrial ', 'p'),
(347, 'IngenierÃ­a en ComputaciÃ³n e InformÃ¡tica ', 'p'),
(348, 'IngenierÃ­a en ConstrucciÃ³n Civil ', 'p'),
(349, 'IngenierÃ­a en ElectrÃ³nica ', 'p'),
(350, 'IngenierÃ­a en Negocios Internacionales ', 'p'),
(351, 'IngenierÃ­a en Transporte MarÃ­timo ', 'p'),
(352, 'InterpretaciÃ³n Teatral ', 'p'),
(353, 'Medicina China y Acupuntura ', 'p'),
(354, 'NaturopatÃ­a HolÃ­stica ', 'p'),
(355, 'OrientaciÃ³n Familiar ', 'p'),
(356, 'PedagogÃ­a en MatemÃ¡tica ', 'p'),
(357, 'TÃ©cnico JurÃ­dico ', 'p'),
(358, 'TÃ©cnico Universitario en AgronomÃ­a ', 'p'),
(359, 'TÃ©cnico Universitario en ElectrÃ³nica ', 'p'),
(360, 'TÃ©cnico Universitario en NaturopatÃ­a ', 'p'),
(361, 'TÃ©cnico Universitario en Negocios Internacion ', 'p'),
(362, 'TÃ©cnico Universitario en Paisajismo ', 'p'),
(363, 'TÃ©cnico Universitario Industrial ', 'p'),
(364, 'Terapeuta Ocupacional ', 'p'),
(365, 'Trabajo Social ', 'p'),
(366, 'Traductor e IntÃ©rprete ', 'p'),
(367, 'Artes Visuales & FotografÃ­a ', 'p'),
(368, 'ComunicaciÃ³n Audiovisual especialidad Cine ', 'p'),
(369, 'ComunicaciÃ³n Audiovisual especialidad Guiones ', 'p'),
(370, 'ComunicaciÃ³n Audiovisual especialidad Television ', 'p'),
(371, 'ComunicaciÃ³n Multimedia especialidad AnimaciÃ³n ', 'p'),
(372, 'ComunicaciÃ³n Multimedia especialidad Internet ', 'p'),
(373, 'Danza & CoreografÃ­a ', 'p'),
(374, 'DiseÃ±o de Imagen & Estilo especialidad Direccion ', 'p'),
(375, 'DiseÃ±o de Imagen & Estilo especialidad ', 'p'),
(376, 'DiseÃ±o de Imagen & Estilo especialidad Moda ', 'p'),
(377, 'MÃºsica & Sonido ', 'p'),
(378, 'Teatro y ComunicaciÃ³n EscÃ©nica ', 'p'),
(379, 'TraducciÃ³n e Interpretariado ', 'p'),
(380, 'Bellas Artes ', 'p'),
(381, 'DiseÃ±o EscÃ©nico Integral ', 'p'),
(382, 'FotografÃ­a Profesional ', 'p'),
(383, 'Historia y Ciencias Sociales ', 'p'),
(384, 'Lengua y Literatura Inglesa ', 'p'),
(385, 'PedagogÃ­a en Danza ', 'p'),
(386, 'PedagogÃ­a en FilosofÃ­a ', 'p'),
(387, 'PlanificaciÃ³n y GestiÃ³n Local ', 'p'),
(388, 'AnÃ¡lisis de Sistemas ', 'p'),
(389, 'Artes EscÃ©nicas ', 'p'),
(390, 'Asistente Judicial ', 'p'),
(391, 'Conectividad y Redes ', 'p'),
(392, 'DiseÃ±o de Interiores menciÃ³n Paisajismo ', 'p'),
(393, 'IngenierÃ­a EjecuciÃ³n InformÃ¡tica ', 'p'),
(394, 'PedagogÃ­a en Castellano ', 'p'),
(395, 'PedagogÃ­a en InglÃ©s EnseÃ±anza Media ', 'p'),
(396, 'Preparador FÃ­sico y Entrenador Personal ', 'p'),
(397, 'Telecomunicaciones ', 'p'),
(398, 'AnimaciÃ³n Digital ', 'p'),
(399, 'ComunicaciÃ³n Audiovisual y Multimedia ', 'p'),
(400, 'CreaciÃ³n e InterpretaciÃ³n Musical ', 'p'),
(401, 'DiseÃ±o ', 'p'),
(402, 'IngenierÃ­a Civil Industrial ', 'p'),
(403, 'IngenierÃ­a en EjecuciÃ³n en InformÃ¡tica ', 'p'),
(404, 'IngenierÃ­a en EjecuciÃ³n Industrial ', 'p'),
(405, 'IngenierÃ­a en Sonido ', 'p'),
(406, 'InterpretaciÃ³n en Canto ', 'p'),
(407, 'InterpretaciÃ³n en Danza ', 'p'),
(408, 'PedagogÃ­a en MatemÃ¡tica y EstadÃ­stica ', 'p'),
(409, 'Teatro y ComunicaciÃ³n EscÃ©nica ', 'p'),
(410, 'TÃ©cnico Universitario en ComputaciÃ³n ', 'p'),
(411, 'TÃ©cnico Universitario en Marketing de Negocio ', 'p'),
(412, 'TraducciÃ³n e IntÃ©rprete en InglÃ©s ', 'p'),
(413, 'Arte ', 'p'),
(414, 'Bachillerato en Humanidades y Ciencias Social ', 'p'),
(415, 'Cine ', 'p'),
(416, 'DiseÃ±o de Ambientes y Objetos ', 'p'),
(417, 'DiseÃ±o Digital ', 'p'),
(418, 'IngenierÃ­a en EjecuciÃ³n en AdministraciÃ³n ', 'p'),
(419, 'PedagogÃ­a BÃ¡sica ', 'p'),
(420, 'Publicidad ', 'p'),
(421, 'Cine, Video y TelevisiÃ³n ', 'p'),
(422, 'IngenierÃ­a Civil en ConstrucciÃ³n ', 'p'),
(423, 'IngenierÃ­a de EjecuciÃ³n en Transporte MarÃ­timo ', 'p'),
(424, 'IngenierÃ­a en Comercio Internacional ', 'p'),
(425, 'IngenierÃ­a en ComputaciÃ³n y TecnologÃ­a de la informacion ', 'p'),
(426, 'IngenierÃ­a en EjecuciÃ³n en ComputaciÃ³n ', 'p'),
(427, 'IngenierÃ­a en EjecuciÃ³n en Pesca y Acuicultura ', 'p'),
(428, 'IngenierÃ­a en EjecuciÃ³n InformÃ¡tica ', 'p'),
(429, 'IngenierÃ­a en GestiÃ³n EstratÃ©gica de Marketing ', 'p'),
(430, 'IngenierÃ­a en LogÃ­stica ', 'p'),
(431, 'IngenierÃ­a en Medio Ambiente y Recursos Naturales ', 'p'),
(432, 'IngenierÃ­a en PrevenciÃ³n de Riesgos y Medio Ambiente ', 'p'),
(433, 'Licenciatura en CriminalÃ­stica ', 'p'),
(434, 'Medicina ', 'p'),
(435, 'TÃ©cnico AgrÃ­cola ', 'p'),
(436, 'TÃ©cnico en Medicina Veterinaria ', 'p'),
(437, 'TÃ©cnico Universitario AgrÃ­cola ', 'p'),
(438, 'TÃ©cnico Universitario en Comercio Exterior ', 'p'),
(439, 'TÃ©cnico Universitario en DiseÃ±o GrÃ¡fico ', 'p'),
(440, 'TÃ©cnico Universitario en Medicina Veterinaria ', 'p'),
(441, 'TÃ©cnico Universitario en Medio Ambiente ', 'p'),
(442, 'TÃ©cnico Universitario en NutriciÃ³n ', 'p'),
(443, 'TÃ©cnico Universitario en PreparaciÃ³n FÃ­sica ', 'p'),
(444, 'TÃ©cnico Universitario en Transporte MarÃ­timo ', 'p'),
(445, 'TÃ©cnico Universitario en Turismo y HotelerÃ­a ', 'p'),
(446, 'TÃ©cnico Universitario Perito Forense ', 'p'),
(447, 'AdministraciÃ³n de Servicios ', 'p'),
(448, 'Bachillerato en Humanidades ', 'p'),
(449, 'Doble Licenciatura FilosofÃ­a - ComunicaciÃ³n ', 'p'),
(450, 'Doble Licenciatura IngenierÃ­a Comercial ', 'p'),
(451, 'IngenierÃ­a ', 'p'),
(452, 'OdontologÃ­a ', 'p'),
(453, 'ComunicaciÃ³n Multimedia ', 'p'),
(454, 'DirecciÃ³n y ProducciÃ³n de Eventos ', 'p'),
(455, 'DiseÃ±o de Vestuario y Textiles ', 'p'),
(456, 'EducaciÃ³n FÃ­sica ', 'p'),
(457, 'IngenierÃ­a en GestiÃ³n AeronÃ¡utica ', 'p'),
(458, 'MÃºsica y TecnologÃ­a ', 'p'),
(459, 'PsicologÃ­a VisiÃ³n Humanista Transpersonal ', 'p'),
(460, 'DiseÃ±o Interior ', 'p'),
(461, 'EducaciÃ³n BÃ¡sica ', 'p'),
(462, 'IngenierÃ­a en GestiÃ³n de Negocios ', 'p'),
(463, 'IngenierÃ­a en Medioambiente ', 'p'),
(464, 'IngenierÃ­a en Sortware ', 'p'),
(465, 'PedagogÃ­a en Artes ', 'p'),
(466, 'PedagogÃ­a en BiologÃ­a ', 'p'),
(467, 'PedagogÃ­a en Historia ', 'p'),
(468, 'PedagogÃ­a en Literatura ', 'p'),
(469, 'PedagogÃ­a en QuÃ­mica ', 'p'),
(470, 'TecnologÃ­a en AdministraciÃ³n de Empresas ', 'p'),
(471, 'TecnologÃ­a en InformÃ¡tica ', 'p'),
(472, 'TecnologÃ­a en PrevenciÃ³n de Riesgos y Medioambiente ', 'p'),
(473, 'Bachillerato en Ciencias Sociales y Humanidades ', 'p'),
(474, 'Ciencias PolÃ­ticas ', 'p'),
(475, 'Contador Auditor ', 'p'),
(476, 'Historia ', 'p'),
(477, 'IngenierÃ­a Civil en InformÃ¡tica y Telecomunicion ', 'p'),
(478, 'IngenierÃ­a Civil en Obras Civiles ', 'p'),
(479, 'IngenierÃ­a en Control de GestiÃ³n ', 'p'),
(480, 'IngenierÃ­a en Finanzas ', 'p'),
(481, 'IngenierÃ­a en Industria y LÃ³gica ', 'p'),
(482, 'IngenierÃ­a en InformÃ¡tica y GestiÃ³n ', 'p'),
(483, 'IngenierÃ­a en Marketing ', 'p'),
(484, 'Artes. Menciones: Escultura, Pintura, Grabado ', 'p'),
(485, 'Ciencias de la Familia ', 'p'),
(486, 'EducaciÃ³n General BÃ¡sica ', 'p'),
(487, 'PedagogÃ­a EducaciÃ³n Media ', 'p'),
(488, 'PedagogÃ­a en ReligiÃ³n ', 'p'),
(489, 'Periodismo ', 'p'),
(490, 'AdministraciÃ³n de Empresas ', 'p'),
(491, 'AdministraciÃ³n de Empresas en Marketing ', 'p'),
(492, 'AdministraciÃ³n de Organizaciones Deportivas ', 'p'),
(493, 'ConstrucciÃ³n Civil y GestiÃ³n de Empresas ', 'p'),
(494, 'DiseÃ±o Crossmedia ', 'p'),
(495, 'FilosofÃ­a ', 'p'),
(496, 'IngenierÃ­a Civil en Estructuras y Geotecnia ', 'p'),
(497, 'IngenierÃ­a Comercial menciÃ³n AdministraciÃ³n ', 'p'),
(498, 'IngenierÃ­a de EjecuciÃ³n Web Manager ', 'p'),
(499, 'Licenciatura en EnseÃ±anza Media ', 'p'),
(500, 'ProducciÃ³n CrossMedia en GrÃ¡fica, Web y Video ', 'p'),
(501, 'AgronomÃ­a menciÃ³n Cultivos y Hortalizas ', 'p'),
(502, 'AgronomÃ­a menciÃ³n Fruitucultura y EnologÃ­a ', 'p'),
(503, 'IngenierÃ­a de EjecuciÃ³n en BiomÃ©dica ', 'p'),
(504, 'IngenierÃ­a en Alimentos ', 'p'),
(505, 'IngenierÃ­a en CriminalÃ­stica ', 'p'),
(506, 'IngenierÃ­a en EjecuciÃ³n ElectrÃ³nica ', 'p'),
(507, 'IngenierÃ­a en EjecuciÃ³n en Industria Alimentacion ', 'p'),
(508, 'Licenciatura de Ciencias de la Familia ', 'p'),
(509, 'PedagogÃ­a en FÃ­sica y MatemÃ¡ticas ', 'p'),
(510, 'PedagogÃ­a en QuÃ­mica y BiologÃ­a ', 'p'),
(511, 'ArqueologÃ­a ', 'p'),
(512, 'ConservaciÃ³n y RestauraciÃ³n de Bienes Cultural ', 'p'),
(513, 'FonoaudiologÃ­a Educacional ', 'p'),
(514, 'Historia del Arte ', 'p'),
(515, 'IngenierÃ­a en InformÃ¡tica de Sistemas ', 'p'),
(516, 'IngenierÃ­a en Redes y Conectividad ', 'p'),
(517, 'PlanificaciÃ³n y GestiÃ³n TurÃ­stica ', 'p'),
(518, 'Ciencia PolÃ­tica ', 'p'),
(519, 'DiseÃ±o GrÃ¡fico y Multimedia ', 'p'),
(520, 'PedagogÃ­a en Artes Visuales ', 'p'),
(521, 'PedagogÃ­a en Historia y GeografÃ­a ', 'p'),
(522, 'ComunicaciÃ³n Audiovisual ', 'p'),
(523, 'ComunicaciÃ³n Organizacional ', 'p'),
(524, 'Danza ', 'p'),
(525, 'DiseÃ±o de Ambientes ', 'p'),
(526, 'DiseÃ±o de AnimaciÃ³n Digital ', 'p'),
(527, 'DiseÃ±o GrÃ¡fico ', 'p'),
(528, 'DiseÃ±o Industrial ', 'p'),
(529, 'IngenierÃ­a Civil Industrial espec. InformÃ¡tica ', 'p'),
(530, 'IngenierÃ­a de EjecuciÃ³n ElectrÃ³nica espec. Telecomicaciones ', 'p'),
(531, 'Terapia Ocupacional ', 'p'),
(532, 'EducaciÃ³n Especial ', 'p'),
(533, 'Bachillerato en Artes ', 'p'),
(534, 'Bachillerato en Ciencias ', 'p'),
(535, 'BiologÃ­a Marina ', 'p'),
(536, 'Ecoturismo ', 'p'),
(537, 'EducaciÃ³n Musical ', 'p'),
(538, 'IngenierÃ­a en AutomatizaciÃ³n y RobÃ³tica ', 'p'),
(539, 'IngenierÃ­a en BiotecnologÃ­a ', 'p'),
(540, 'IngenierÃ­a en ConstrucciÃ³n ', 'p'),
(541, 'IngenierÃ­a en GestiÃ³n InformÃ¡tica ', 'p'),
(542, 'IngenierÃ­a en LogÃ­stica y Transporte ', 'p'),
(543, 'IngenierÃ­a en Redes y ComunicaciÃ³n de Datos ', 'p'),
(544, 'IngenierÃ­a en Seguridad y PrevenciÃ³n de riesgos ', 'p'),
(545, 'IngenierÃ­a en Turismo y HotelerÃ­a ', 'p'),
(546, 'IngenierÃ­a FÃ­sica ', 'p'),
(547, 'IngenierÃ­a Industrial ', 'p'),
(548, 'Licenciatura en Literatura ', 'p'),
(549, 'NutriciÃ³n y DietÃ©tica ', 'p'),
(550, 'PsicopedagogÃ­a ', 'p'),
(551, 'Ciencias CriminalÃ­stico ', 'p'),
(552, 'EducaciÃ³n BÃ¡sica m/ InformÃ¡tica Educativa ', 'p'),
(553, 'EducaciÃ³n Esp. MenciÃ³n Dificultades del Aprendisaje ', 'p'),
(554, 'EducaciÃ³n Parvularia menciÃ³n ExpresiÃ³n ArtÃ­stica ', 'p'),
(555, 'GestiÃ³n Hotelera BilingÃ¼e ', 'p'),
(556, 'GuÃ­a BilingÃ¼e de Turismo Aventura ', 'p'),
(557, 'Salud Natural Intregativa ', 'p'),
(558, 'EducaciÃ³n FÃ­sica y Deportes ', 'p'),
(559, 'Ciencias PolÃ­ticas y GestiÃ³n PÃºblica ', 'p'),
(560, 'IngenierÃ­a en Turismo ', 'p'),
(561, 'PedagogÃ­a en Historia y Ciencias Sociales ', 'p'),
(562, 'TÃ©cnico en EnfermerÃ­a ', 'p'),
(563, 'ActuaciÃ³n ', 'p'),
(564, 'Bachillerato en Ciencias Sociales ', 'p'),
(565, 'BiotecnologÃ­a ', 'p'),
(566, 'EducaciÃ³n BÃ¡sica ', 'p'),
(567, 'IngenierÃ­a en EjecuciÃ³n Agropecuaria ', 'p'),
(568, 'TecnologÃ­a MÃ©dica ', 'p'),
(569, 'DirecciÃ³n de arte ', 'p'),
(570, 'DiseÃ±o de objetos y ambientes ', 'p'),
(571, 'DiseÃ±o de vestuario ', 'p'),
(572, 'DiseÃ±o teatral ', 'p'),
(573, 'FotografÃ­a ', 'p'),
(574, 'IngenierÃ­a civil en sonido y acÃºstica ', 'p'),
(575, 'IngenierÃ­a en automatizaciÃ³n y control industrial ', 'p'),
(576, 'PedagogÃ­a en artes musicales ', 'p'),
(577, 'PedagogÃ­a en artes y diseÃ±o ', 'p'),
(578, 'PedagogÃ­a en teorÃ­a e historia del arte ', 'p'),
(579, 'ProducciÃ³n musical ', 'p'),
(580, 'TecnologÃ­a en sonido ', 'p'),
(581, 'Terapia artÃ­stica menciÃ³n artes visuales ', 'p'),
(582, 'Terapia artÃ­stica menciÃ³n mÃºsica ', 'p'),
(583, 'Terapia del lenguaje ', 'p'),
(584, 'AdministraciÃ³n de Empresas ', 'tp'),
(585, 'Contabilidad ', 'tp'),
(586, 'GestiÃ³n de Calidad ', 'tp'),
(587, 'Asistente Ejecutivo ', 'tp'),
(588, 'PrevenciÃ³n de Riesgos ', 'tp'),
(589, 'JurÃ­dico ', 'tp'),
(590, 'fotografÃ­a periodÃ­stica ', 'tp'),
(591, 'fotografÃ­a publicitaria ', 'tp'),
(592, 'fotografÃ­a ', 'tp'),
(593, 'ilustraciÃ³n artÃ­stica ', 'tp'),
(594, 'gestiÃ³n y producciÃ³n de eventos ', 'tp'),
(595, 'diseÃ±o y producciÃ³n de grÃ¡fica digital ', 'tp'),
(596, 'diplomado en fotografÃ­a digital ', 'tp'),
(597, 'diplomado en gestiÃ³n cultural ', 'tp'),
(598, 'Agente de Ventas MenciÃ³n Visitador MÃ©dico ', 'tp'),
(599, 'Laboratorista Dental ', 'tp'),
(600, 'podologia ', 'tp'),
(601, 'auxiliar paramedico ', 'tp'),
(602, 'manejo de computadores ', 'tp'),
(603, 'seguridad os10 ', 'tp'),
(604, 'gasfiterÃ­a ', 'tp'),
(605, 'GestiÃ³n Financiera e Inversiones ', 'tp'),
(606, 'AnÃ¡lisis de Sistemas ', 'tp'),
(607, 'Asistente Computacional BilingÃ¼e ', 'tp'),
(608, 'Comercio Exterior ', 'tp'),
(609, 'DecoraciÃ³n de Interiores ', 'tp'),
(610, 'Dibujo TÃ©cnico ', 'tp'),
(611, 'Secretariado Ejecutivo BilingÃ¼e ', 'tp'),
(612, 'Secretariado Ejecutivo Computacional ', 'tp'),
(613, 'Soporte En Redes Computacionales ', 'tp'),
(614, 'TÃ©cnico JurÃ­dico ', 'tp'),
(615, 'Turismo ', 'tp'),
(616, 'Ventas y NegociaciÃ³n Comercial ', 'tp'),
(617, 'diseÃ±o artÃ­stico de vestuario ', 'tp'),
(618, 'diseÃ±o de vestuario computacional ', 'tp'),
(619, 'alta costura corte y diseÃ±o de vestuario ', 'tp'),
(620, 'tÃ©cnico de nivel superior en diseÃ±o de vestuario ', 'tp'),
(621, 'Asistente Juridico ', 'tp'),
(622, 'TÃ©cnico en ComputaciÃ³n ', 'tp'),
(623, 'TÃ©c. Asistente De Educ. Parvularia ', 'tp'),
(624, 'Turismo y HotelerÃ­a ', 'tp'),
(625, 'Secretariado EjecuciÃ³n JurÃ­dico ComputaciÃ³n ', 'tp'),
(626, 'Contabilidad y AuditorÃ­a ', 'tp'),
(627, 'TÃ©cnico de Nivel Superior en Deportes ', 'tp'),
(628, 'TÃ©cnico de Nivel Superior en EnfermerÃ­a ', 'tp'),
(629, 'TÃ©cnico de Nivel Superior en OdontologÃ­a ', 'tp'),
(630, 'TÃ©cnico de Nivel Superior en PreparaciÃ³n FÃ­sica ', 'tp'),
(631, 'TÃ©cnico de Nivel Superior en GestiÃ³n y Soporte de Redes ', 'tp'),
(632, 'TÃ©cnico de Nivel Superior en AnÃ¡lisis de Sistemas ', 'tp'),
(633, 'TÃ©cnico de Nivel Superior en DiseÃ±o GrÃ¡fico y ProducciÃ³n Digital ', 'tp'),
(634, 'TÃ©cnico de Nivel Superior en Contabilidad General ', 'tp'),
(635, 'TÃ©cnico de Nivel Superior en GastronomÃ­a y Cocina ', 'tp'),
(636, 'TÃ©cnico de Nivel Superior en PrevenciÃ³n de Riesgos y Medio Ambiente ', 'tp'),
(637, 'TÃ©cnico de Nivel Superior en ConstrucciÃ³n ', 'tp'),
(638, 'TÃ©cnico de Nivel Superior en ElectrÃ³nica Industrial, MenciÃ³n Control AutomÃ¡t', 'tp'),
(639, 'TÃ©cnico de Nivel Superior JurÃ­dico ', 'tp'),
(640, 'tecnico superior juridico ', 'tp'),
(641, 'tecnico superior en farmacia ', 'tp'),
(642, 'tecnico superior en estetica integral y cosmetologia ', 'tp'),
(643, 'tecnico superior audio-protesista ', 'tp'),
(644, 'tecnico superior en alimentos y nutriciÃ³n ', 'tp'),
(645, 'tecnico superior en ciencias de la familia y mediacion ', 'tp'),
(646, 'optica ', 'tp'),
(647, 'tecnico superior en educacion especial y diferenciada ', 'tp'),
(648, 'Contador Auditor ', 'tp'),
(649, 'IngenierÃ­a en AdministraciÃ³n de Empresas ', 'tp'),
(650, 'NutriciÃ³n y DietÃ©tica ', 'tp'),
(651, 'IngenierÃ­a en InformÃ¡tica ', 'tp'),
(652, 'IngenierÃ­a en ConstrucciÃ³n ', 'tp'),
(653, 'IngenierÃ­a en prevenciÃ³n de riesgos. ', 'tp'),
(654, 'Artes Culinarias y GastronomÃ­a Internacional ', 'tp'),
(655, 'ComunicaciÃ³n Audiovisual con menciÃ³n en DirecciÃ³n y ProducciÃ³n de TV ', 'tp'),
(656, 'DirecciÃ³n y producciÃ³n de eventos ', 'tp'),
(657, 'DiseÃ±o de Vestuario con MenciÃ³n en ConfecciÃ³n y Moldaje Industrial ', 'tp'),
(658, 'administraciÃ³n de empresas y contabilidad ', 'tp'),
(659, 'auxiliar de pÃ¡rvulos computacional ', 'tp'),
(660, 'asistente jurÃ­dico computacional ', 'tp'),
(661, 'ingles ejecutivo ', 'tp'),
(662, 'operaciÃ³n de computadores ', 'tp'),
(663, 'digitaciÃ³n en entrada de datos ', 'tp'),
(664, 'TÃ©cnico en Agricultura EcolÃ³gica ', 'tp'),
(665, 'TÃ©cnico en Ecoturismo ', 'tp'),
(666, 'TÃ©cnico en EnergÃ­as Renovables y Eficiencia EnergÃ©tica ', 'tp'),
(667, 'TÃ©cnico en Medio Ambiente ', 'tp'),
(668, 'TÃ©cnico en Paisajismo ', 'tp'),
(669, 'TÃ©cnico en Salud y Terapias Naturales ', 'tp'),
(670, 'TÃ©cnico en MinerÃ­a y GeologÃ­a ', 'tp'),
(671, 'TÃ©cnico en PrevenciÃ³n de Riesgos y Medio Ambiente ', 'tp'),
(672, 'TÃ©cnico Veterinario ', 'tp'),
(673, 'tecnico en enfermeria ', 'tp'),
(674, 'cocina nacional e internacional ', 'tp'),
(675, 'secretariado gerencial bilingÃ¼e ', 'tp'),
(676, 'mecanica automotriz ', 'tp'),
(677, 'tecnico en educacion parvularia ', 'tp'),
(678, 'administracion y gestion de empresas ', 'tp'),
(679, 'masoterapia ', 'tp'),
(680, 'tecnico juridico prevencion de riesgos ', 'tp'),
(681, 'redes y telecomunicaciones ', 'tp'),
(682, 'soporte computacional ', 'tp'),
(683, 'diseÃ±o grafico computacional ', 'tp'),
(684, 'fotografÃ­a y comunicaciÃ³n visual ', 'tp'),
(685, 'comercio exterior y relaciones internacionales ', 'tp'),
(686, 'tÃ©cnico deportivo ', 'tp'),
(687, 'Turismo de Aventura ', 'tp'),
(688, 'AdministraciÃ³n Hotelera ', 'tp'),
(689, 'Turismo TÃ©cnico MenciÃ³n Empresas TurÃ­sticas ', 'tp'),
(690, 'Turismo TÃ©cnico MenciÃ³n Servicios Aerocomerciales ', 'tp'),
(691, 'GastronomÃ­a ', 'tp'),
(692, 'Analista Programador Computacional ', 'tp'),
(693, 'TÃ©cnico en Telecomunicaciones ', 'tp'),
(694, 'Dibujo ArquitectÃ³nico y Estructural ', 'tp'),
(695, 'TÃ©cnico en Instalaciones ElÃ©ctricas ', 'tp'),
(696, 'TÃ©cnico en PrevenciÃ³n de Riesgos PEV ', 'tp'),
(697, 'TÃ©cnico TopÃ³grafo ', 'tp'),
(698, 'RestauraciÃ³n Patrimonial ', 'tp'),
(699, 'TecnologÃ­a en Sonido ', 'tp'),
(700, 'Publicidad TÃ©cnica MenciÃ³n ProducciÃ³n Digital ', 'tp'),
(701, 'TÃ©cnico Audiovisual ', 'tp'),
(702, 'AdministraciÃ³n de Recursos Humanos ', 'tp'),
(703, 'AdministraciÃ³n Financiera ', 'tp'),
(704, 'Contabilidad General M/LegislaciÃ³n Tributaria ', 'tp'),
(705, 'AdministraciÃ³n de Empresas MenciÃ³n Marketing ', 'tp'),
(706, 'AdministraciÃ³n de Ventas ', 'tp'),
(707, 'TÃ©cnico en Servicios Financieros y Bancarios ', 'tp'),
(708, 'TÃ©cnico en GestiÃ³n LogÃ­stica ', 'tp'),
(709, 'TÃ©cnico en MecÃ¡nica Automotriz y AutotrÃ³nica ', 'tp'),
(710, 'TÃ©cnico en Electricidad y ElectrÃ³nica ', 'tp'),
(711, 'TÃ©cnico en InstrumentaciÃ³n y AutomatizaciÃ³n Industrial ', 'tp'),
(712, 'TÃ©cnico en Maquinaria y VehÃ­culos Pesados ', 'tp'),
(713, 'TÃ©cnico en Mantenimiento Industrial ', 'tp'),
(714, 'TÃ©cnico en EnergÃ­a Renovable y Eficiencia EnergÃ©tica ', 'tp'),
(715, 'TÃ©cnico en DiseÃ±o GrÃ¡fico ', 'tp'),
(716, 'IlustraciÃ³n Digital ', 'tp'),
(717, 'TÃ©cnico AgrÃ­cola ', 'tp'),
(718, 'TÃ©cnico en OdontologÃ­a ', 'tp'),
(719, 'Fisioterapeuta Deportivo ', 'tp'),
(720, 'Preparador FÃ­sico ', 'tp'),
(721, 'TÃ©cnico de EnfermerÃ­a ', 'tp'),
(722, 'TÃ©cnico de Laboratorio ClÃ­nico y Banco de Sangre ', 'tp'),
(723, 'TÃ©cnico de RadiodiagnÃ³stico y Radioterapia ', 'tp'),
(724, 'tecnico financiero ', 'tp'),
(725, 'tecnico en gestion de servicios financieros ', 'tp'),
(726, 'tecnico en comercio internacional ', 'tp'),
(727, 'TÃ©cnico de Nivel Superior en AdministraciÃ³n en Salud ', 'tp'),
(728, 'TÃ©cnico de Nivel Superior en EnfermerÃ­a ObstÃ©trica ', 'tp'),
(729, 'TÃ©cnico de Nivel Superior en PodologÃ­a ', 'tp'),
(730, 'TÃ©cnico de Nivel Superior en Terapias Naturales ', 'tp'),
(731, 'TÃ©cnico Dental (Plan Especial) ', 'tp'),
(732, 'TÃ©cnico Dental de Nivel Superior menciÃ³n Asistente, Higienista y Laboratorista', 'tp'),
(733, 'TÃ©cnico en EnfermerÃ­a con NivelaciÃ³n ', 'tp'),
(734, 'TÃ©cnico en EnfermerÃ­a Plan EstÃ¡ndar ', 'tp'),
(735, 'Auditoria (CSI) ', 'tp'),
(736, 'Contador General ', 'tp'),
(737, 'IngenierÃ­a de EjecuciÃ³n en AdministraciÃ³n de Empresas ', 'tp'),
(738, 'Ingenieria de EjecuciÃ³n en AdministraciÃ³n PÃºblica ', 'tp'),
(739, 'IngenierÃ­a de EjecuciÃ³n en AdministraciÃ³n PÃºblica, CSI ', 'tp'),
(740, 'IngenierÃ­a en GestiÃ³n Empresarial ', 'tp'),
(741, 'Secretariado Ejecutivo Bilingue menciÃ³n Comercio Exterior ', 'tp'),
(742, 'TÃ©cnico de Nivel Superior en AdministraciÃ³n de Empresas menciÃ³n RR.HH ', 'tp'),
(743, 'TÃ©cnico de Nivel Superior en AdministraciÃ³n PÃºblica ', 'tp'),
(744, 'TÃ©cnico de Nivel Superior en Auditoria ', 'tp'),
(745, 'TÃ©cnico JurÃ­dico de Nivel Superior menciÃ³n DocumentologÃ­a ', 'tp'),
(746, 'ConstrucciÃ³n Civil ', 'tp'),
(747, 'EducaciÃ³n Parvularia ', 'tp'),
(748, 'PedagogÃ­a en Historia y GeografÃ­a ', 'tp'),
(749, 'PedagogÃ­a en InglÃ©s ', 'tp'),
(750, 'PsicopedagogÃ­a ', 'tp'),
(751, 'TÃ©cnico de Nivel Superior en Deporte y RecreaciÃ³n ', 'tp'),
(752, 'TÃ©cnico de Nivel Superior en EducaciÃ³n Parvularia ', 'tp'),
(753, 'TÃ©cnico de Nivel Superior en EducaciÃ³n Parvularia menciÃ³n InglÃ©s ', 'tp'),
(754, 'TÃ©cnico de Nivel Superior en Trabajo Social ', 'tp'),
(755, 'TÃ©cnico de Nivel Superior en TraducciÃ³n InglÃ©s EspaÃ±ol ', 'tp'),
(756, 'TÃ©cnico en AdministraciÃ³n de Empresas menciÃ³n Marketing y ComunicaciÃ³n ', 'tp'),
(757, 'TÃ©cnico en EducaciÃ³n Diferencial ', 'tp'),
(758, 'Trabajo Social ', 'tp'),
(759, 'IngenierÃ­a de EjecuciÃ³n en PrevenciÃ³n de Riesgos y Medio Ambiente ', 'tp'),
(760, 'ProgramaciÃ³n de Computadores ', 'tp'),
(761, 'TÃ©cnico Agricola de Nivel Superior ', 'tp'),
(762, 'TÃ©cnico de Nivel Superior en InformÃ¡tica ', 'tp'),
(763, 'TÃ©cnico de Nivel Superior en InformÃ¡tica menciÃ³n Seguridad ', 'tp'),
(764, 'TÃ©cnico de Nivel Superior en InformÃ¡tica y Redes ', 'tp'),
(765, 'TÃ©cnico de NIvel Superior en Metalurgia ', 'tp'),
(766, 'TÃ©cnico de Nivel Superior en MinerÃ­a ', 'tp'),
(767, 'TÃ©cnico de Nivel Superior en TopografÃ­a ', 'tp'),
(768, 'TÃ©cnico en Nivel Superior en GeologÃ­a ', 'tp'),
(769, 'DiseÃ±o GrÃ¡fico Publicitario ', 'tp'),
(770, 'TÃ©cnico de Nivel Superior en DiseÃ±o Digital menciÃ³n IlustraciÃ³n ', 'tp'),
(771, 'TÃ©cnico de Nivel Superior en FotografÃ­a menciÃ³n Artistica y Comercial ', 'tp'),
(772, 'TÃ©cnico de Nivel Superior en FotografÃ­a PeriodÃ­stica y Publicitaria ', 'tp'),
(773, 'TÃ©cnico de Nivel Superior en FotografÃ­a, Arte y ComunicaciÃ³n ', 'tp'),
(774, 'Contabilidad ', 't'),
(775, 'AdministraciÃ³n de empresas ', 't'),
(776, 'ElectrÃ³nica ', 't'),
(777, 'Electricidad ', 't'),
(778, 'AlimentaciÃ³n ', 't'),
(779, 'PÃ¡rvulos ', 't'),
(780, 'EnfermerÃ­a ', 't'),
(781, 'MecÃ¡nica automotriz ', 't'),
(782, 'Turismo ', 't'),
(783, 'Secretariado ', 't'),
(784, 'Telecomunicaciones ', 't');


--instituciones--

INSERT INTO "MP_institucion"(
            id, nombre, colegio)
    VALUES

(1118, 'liceo instituto nacional', True),
(1119, 'liceo javiera carrera', True),
(1120, 'liceo isaura dinator de guzman', True),
(1121, 'liceo teresa prat de sarratea', True),
(1122, 'liceo nro 2 miguel luis amunategui', True),
(1123, 'liceo de aplicacion rector jorge e schne', True),
(1124, 'liceo manuel barros borgono', True),
(1125, 'liceo confederacion suiza', True),
(1126, 'liceo poliv.lib. gral jose de san martin', True),
(1127, 'liceo dario salas', True),
(1128, 'internado nacional barros arana', True),
(1129, 'liceo industrial eleodoro garcia zegers', True),
(1130, 'liceo politec. pdte. gabriel gonzalez videla', True),
(1131, 'inst.sup.de comercio eduardo frei m.', True),
(1132, 'esc. bas. republica oriental de uruguay', True),
(1133, 'escuela basica provincia de chiloe', True),
(1134, 'escuela basica republica de colombia', True),
(1135, 'escuela basica republica de panama', True),
(1136, 'escuela cadete arturo prat chacon', True),
(1137, 'escuela basica irene frei de cid', True),
(1138, 'escuela basica libertadores de chile', True),
(1139, 'escuela basica benjamin vicuna mackenna', True),
(1140, 'liceo republica de brasil', True),
(1141, 'escuela republica de israel', True),
(1142, 'escuela basica republica de haiti', True),
(1143, 'escuela especial adultos penitencieria', True),
(1144, 'escuela basica dr luis calvo mackenna', True),
(1145, 'escuela fernando alessandri rodriguez', True),
(1147, 'esc. esp. leng. cardenal raul silva h.', True),
(1148, 'escuela bas salvador sanfuentes rep eeuu', True),
(1149, 'liceo municipal metropolitano de adultos', True),
(1150, 'escuela republica el libano', True),
(1151, 'escuela republica de alemania', True),
(1152, 'escuela basica de chile', True),
(1153, 'escuela basica republica de mexico', True),
(1154, 'esc. diferencial edmundo de amicis', True),
(1155, 'escuela basica republica del ecuador', True),
(1156, 'centro detencion preventiva de menores', True),
(1157, 'escuela basica reina victoria', True),
(1158, 'escuela basica reyes catolicos', True),
(1159, 'colegio piloto pardo', True),
(1160, 'esc.diferencial republica de sudafrica', True),
(1161, 'esc. centro de capacitacion laboral', True),
(1163, 'escuela diferencial juan sandoval c', True),
(1164, 'miguel de cervantes y saavedra anexo a-8', True),
(1165, 'liceo miguel de cervantes y saavedra', True),
(1166, 'escuela especial apostol', True),
(1167, 'escuela de parv. parque o?higgins', True),
(1168, 'centro educativo ochagavia', True),
(1169, 'escuela poetas de chile', True),
(1170, 'escuela la victoria', True),

(171, 'liceo municipal enrique backausse', True),
(172, 'escuela centro educ. rep. mexicana', True),
(173, 'escuela poeta gonzalo rojas', True),
(174, 'escuela basica ricardo e. latchman', True),
(175, 'escuela de parvulos rayito de luz', True),
(176, 'escuela boroa', True),
(177, 'liceo polivalente eugenio pereira salas', True),
(178, 'escuela lo valledor', True),
(179, 'escuela ciudad de barcelona', True),
(180, 'escuela villa sur', True),
(181, 'colegio parque las americas', True),
(182, 'esc. basica municipal risopatron', True),
(183, 'liceo luis galecio corvera', True),
(184, 'liceo betsabe hormazabal de alarcon', True),
(185, 'liceo andres bello', True),
(186, 'esc. bas. gabriela mistral de', True),
(187, 'escuela general basica santa fe', True),
(188, 'escuela territorio antartico', True),
(189, 'escuela llano subercaseaux', True),
(190, 'escuela villa', True),
(191, 'escuela basica municipal', True),
(192, 'escuela especial los cedros del libano', True),
(193, 'inst. reg. educ adultos', True),
(194, 'esc. esp. de adultos hugo morales bizama', True),
(195, 'centro educacional horacio aravena a.', True),
(196, 'escuela basica ciudad de frankfort', True),
(198, 'escuela basica fray camilo henriquez', True),
(199, 'escuela poeta victor domingo silva', True),
(200, 'centro educ. provincia de Ã‘uble', True),
(201, 'escuela provincia de nuble', True),
(202, 'esc. bas. y esp. su santidad juan xxiii', True),
(203, 'centro educacional municipal', True),
(204, 'escuela poeta neruda', True),
(205, 'liceo santa maria eufrasia', True),
(206, 'centro educacional baldomero lillo', True),
(207, 'liceo fidel pinochet le-brun-sn.bernado', True),
(208, 'liceo elvira brady maldonado-sn.bernardo', True),
(209, 'liceo ind. miguel aylwin gajardo', True),
(210, 'escuela pilar moliner de nuez', True),
(211, 'escuela republica del brasil', True),
(212, 'escuela isabel riquelme', True),
(213, 'escuela l.gral. bernardo o?higgins', True),
(214, 'escuela basica lucila godoy alcayaga', True),
(215, 'liceo poliv. lucila godoy alcayaga', True),
(216, 'escuela general rene schneider chereau', True),
(217, 'escuela alemania', True),
(218, 'escuela republica de los ee.uu. de america', True),
(219, 'escuela javiera carrera verdugo', True),
(220, 'escuela manuel magallanes moure', True),
(221, 'escuela republica del peru', True),
(222, 'escuela diego portales', True),
(223, 'escuela mahuida', True),
(224, 'escuela nuevo porvenir', True),
(225, 'escuela basica dr luis sepulveda salvati', True),
(226, 'escuela escritora marcela paz', True),
(227, 'escuela espana', True),
(228, 'escuela ignacio carrera pinto', True),
(229, 'escuela de educacion diferencial', True),
(230, 'escuela sta. teresa de los morros', True),
(231, 'escuela benjamin viel', True),
(232, 'escuela abraham lincoln', True),
(233, 'escuela basica antupillan', True),
(234, 'liceo de adultos pucara de chena', True),
(235, 'escuela eleodoro yanez ponce de leon', True),
(236, 'escuela cardenal antonio samore', True),
(237, 'escuela haras los condores', True),
(238, 'escuela teresa garcia huidobro', True),
(239, 'liceo clara solovera', True),
(240, 'hernan merino correa', True),
(241, 'liceo industrial hardware', True),
(242, 'escuela basica cinco pinos', True),
(243, 'escuela basica valle de lluta', True),
(244, 'liceo valle de lluta', True),
(245, 'escuela part.comandante carlos condell', True),
(246, 'esc. basica municipalizado jaime guzman errazuriz', True),
(247, 'centro educ. padre alberto hurtado', True),
(248, 'liceo municipal poetisa gabriela mistral', True),
(249, 'colegio lonquen', True),
(250, 'liceo 131', True),
(251, 'escuela rayen mapu', True),
(252, 'colegio de maipo', True),
(253, 'liceo alto jahuel', True),
(254, 'liceo los guindos', True),
(255, 'escuela villaseca', True),
(256, 'liceo francisco javier kruger alvarado', True),
(257, 'escuela valdivia', True),
(258, 'escuela lo salinas', True),
(259, 'escuela humberto moreno ramirez', True),
(260, 'escuela los rosales del bajo', True),
(261, 'escuela viluco', True),
(262, 'escuela andres puig ferrer', True),
(263, 'escuela especial defic mental camposano', True),
(264, 'escuela los aromos de el recurso', True),
(265, 'escuela bas. de adultos agustin calderon roja', True),
(266, 'liceo tecnico profesional', True),
(267, 'centro educ. enrique bernstein carabante', True),
(268, 'escuela alemania', True),
(269, 'escuela de hospital', True),
(270, 'liceo maria carvajal fuenzalida', True),
(271, 'escuela elias sanchez ortuzar', True),
(272, 'escuela barbara kast rist', True),
(273, 'escuela raul sanchez cerda', True),
(274, 'escuela carmen reveco nunez', True),
(275, 'colegio challay', True),
(276, 'escuela ricardo sanchez cerda', True),
(277, 'escuela sendero de culitrin', True),
(278, 'escuela las colonias', True),
(279, 'escuela francisco letelier valdes', True),
(280, 'escuela huelquen', True),
(281, 'escuela aguila sur', True),
(282, 'escuela hugo pino vilchez', True),
(283, 'liceo municipal de adultos miguel campino', True),
(284, 'esc. basica municipal paula jaraquemada', True),
(285, 'centro duc.cardenal jose maria caro', True),
(286, 'liceo polivalente', True),
(287, 'escuela basica salomon sack', True),
(288, 'escuela conquistando futuro', True),
(289, 'escuela blue star college', True),
(290, 'escuela basica santa adriana', True),
(291, 'escuela basica acapulco', True),
(292, 'colegio hernan olguin', True),
(293, 'liceo teniente francisco mery aguirre', True),
(294, 'escuela basica clara estrella', True),
(295, 'escuela raul saez saez', True),
(296, 'escuela basica bernardo o?higgins', True),
(297, 'escuela bas. republica de felipinas', True),
(298, 'escuela basica coeducacional', True),
(299, 'escuela especial de educacion', True),
(300, 'liceo christa mc auliffe', True),
(301, 'liceo juan gomez millas', True),
(302, 'escuela basica aviadores', True),
(303, 'escuela basica mario arce gatica', True),
(304, 'complejo educacional', True),
(305, 'escuela chile california', True),
(306, 'escuela basica villa santa elena', True),
(307, 'escuela ciudad de lyon', True),
(308, 'escuela basica paul harris', True),
(309, 'escuela nemesio antunez', True),
(311, 'liceo elena caffarena morice', True),
(312, 'escuela marcial martinez ferrari', True),
(313, 'escuela general alberto a. bachelet martinez', True),
(314, 'escuela bernardo leighton', True),
(315, 'escuela claudio arrau leon', True),
(316, 'escuela orlando letelier', True),
(317, 'escuela basica fray luis beltran', True),
(318, 'centro educacional matias cousino', True),
(319, 'colegio batalla de la concepcion', True),
(320, 'esc. bas. pdte. salvador allende g.', True),
(321, 'escuela bas. los heroes de yungay', True),
(322, 'liceo polivalente francisco frias v.', True),
(323, 'escuela basica dr alejandro del rio', True),
(324, 'liceo doctor alejandro del rio', True),
(325, 'escuela bas. malaquias concha', True),
(326, 'liceo malaquias concha', True),
(327, 'escuela bas. tecno sur', True),
(328, 'escuela basica ventura maturana barahona', True),
(329, 'escuela belgica', True),
(330, 'colegio municipal proceres de chile', True),
(331, 'escuela bas. la araucania', True),
(332, 'escuela diferencial santa teresita de los andes', True),
(333, 'escuela bas. sanitas', True),
(334, 'escuela bas. poeta oscar castro zuniga', True),
(335, 'escuela basica islas de chile', True),
(336, 'liceo municipal poeta neruda', True),
(337, 'escuela bas. benjamin subercaseaux', True),
(338, 'escuela bas. reina guillermina de holanda', True),
(339, 'liceo politecnico abdon cifuentes', True),
(340, 'liceo politecnico ciencia y tecnologia', True),
(341, 'colegio naciones unidas', True),
(342, 'colegio palestino', True),
(343, 'escuela (liceo veneciano )', True),
(344, 'escuela esperanza joven', True),
(345, 'escuela bas. oscar encalada yovanovich', True),
(347, 'escuela basica portal', True),
(348, 'colegio municipal antu', True),
(349, 'escuela sergio silva acuna', True),
(350, 'liceo municipalizado araucania', True),
(351, 'escuela basica sendero del saber', True),
(352, 'escuela basica educadores de chile', True),
(353, 'liceo domingo faustino sarmiento', True),
(354, 'liceo municipal purkuyen', True),
(355, 'escuela ninahue', True),
(356, 'centro educacional municipal', True),
(357, 'centro educacional mirador', True),
(358, 'escuela basica tupahue', True),
(359, 'escuela basica karelmapu', True),
(360, 'escuela basica villa la cultura', True),
(361, 'escuela basica aliven', True),
(362, 'escuela especial de adultos', True),
(363, 'liceo municipalizado amanda labarca', True),
(364, 'colegio antartica chilena', True),
(365, 'colegio san francisco del alba', True),
(366, 'liceo juan pablo ii', True),
(367, 'liceo simon bolivar', True),
(368, 'esc. de educ. diferencial paul harris', True),
(369, 'liceo santa maria', True),
(370, 'colegio leonardo da vinci', True),
(371, 'liceo polivalente arturo alessandri p.', True),
(372, 'liceo a-43 liceo siete de ninas', True),
(373, 'liceo carmela carvajal de prat', True),
(374, 'liceo jose victorino lastarria', True),
(375, 'liceo b 42 tajamar', True),
(376, 'escuela basica el vergel', True),
(377, 'escuela abelardo iturriaga jamett', True),
(378, 'escuela basica juan pablo duarte', True),
(379, 'escuela basica mercedes marin del solar', True),
(380, 'esc. de parv. madre bernarda morin', True),
(381, 'complejo educacional', True),
(382, 'liceo eugenio maria de hostos', True),
(383, 'colegio municipalizado confederac suiza', True),
(384, 'escuela d-231 especial de desarrollo', True),
(385, 'escuela republica de chipre', True),
(386, 'colegio yangtse', True),
(387, 'escuela palestina', True),
(388, 'educ. diferencial exequiel gonzalez', True),
(389, 'escuela benjamin claro velasco', True),
(390, 'liceo augusto d halmar', True),
(391, 'liceo carmela silva donoso', True),
(392, 'liceo jose toribio medina', True),
(393, 'complejo educ.mun. brigida walker.', True),
(394, 'liceo lenka franulic', True),
(395, 'col tec profesional republica argentina', True),
(396, 'escuela diferencial municipal amapolas', True),
(397, 'esc.presidente eduardo frei montalba', True),
(398, 'escuela aurora de chile', True),
(399, 'escuela basica jose toribio medina', True),
(400, 'liceo jose toribio medina anexo', True),
(401, 'escuela republica de francia', True),
(402, 'escuela republica de costa rica', True),
(403, 'liceo republica de siria', True),
(404, 'escuela guillermo zanartu irigoyen', True),
(405, 'escuela de ed.diferencial hellen keller', True),
(406, 'escuela juan moya morales', True),
(407, 'compl.educacional brigida walker anexo', True),
(408, 'centro educ. valle hermoso', True),
(409, 'liceo antonio hermida fabres', True),
(410, 'escuela juan bautista pasten', True),
(411, 'escuela union nacional arabe', True),
(412, 'centro educacional eduardo de la barra', True),
(413, 'centro educacion mariano egana', True),
(414, 'centro educ.erazmo escala arriagada', True),
(415, 'liceo erasmo escala arriagada', True),
(416, 'escuela carlos hernandez pena', True),
(417, 'escuela luis arrieta canas', True),
(418, 'escuela e-180 matilde huici navas', True),
(419, 'escuela tobalaba', True),
(420, 'escuela luis gregorio ossa', True),
(421, 'escuela stgo bueras y avarias', True),
(422, 'escuela especial pontifice juan pablo ii', True),
(423, 'escuela santa maria', True),
(424, 'centro innovativo la puerta', True),
(425, 'liceo mercedes marin del solar', True),
(426, 'liceo polivalente mercedes marin del solar', True),
(427, 'liceo juana de ibarbourou', True),
(428, 'complejo educ. joaquin edwards bello.', True),
(429, 'escuela jose bernardo suarez', True),
(430, 'escuela bas. centro educacional millantu', True),
(431, 'escuela manuel irarrazabal', True),
(432, 'liceo municipalizado manuel rojas', True),
(433, 'escuela enrique molina garmendia', True),
(434, 'escuela julio montt salamanca', True),
(436, 'instituto de educacion de adultos', True),
(437, 'liceo estados americanos', True),
(439, 'colegio adultos fermin vivaceta', True),
(440, 'escuela de farellones', True),
(441, 'complejo educ. eduardo cuevas valdes', True),
(442, 'esc. de parv.beato padre alberto hurtado', True),
(443, 'liceo poliv. san jose', True),
(444, 'liceo diego aracena aguilar', True),
(445, 'liceo bueras y avaria', True),
(446, 'liceo jose ignacio zenteno', True),
(447, 'centro de educ. tecn.profesional codeduc', True),
(448, 'escuela general san martin', True),
(449, 'escuela general ohiggins', True),
(450, 'escuela presidente riesco errazuriz', True),
(451, 'escuela vicente reyes palazuelos', True),
(452, 'escuela ramon freire', True),
(453, 'escuela leon humberto valenzuela', True),
(454, 'escuela el llano', True),
(455, 'escuela reino de dinamarca', True),
(457, 'escuela tomas vargas', True),
(458, 'republica de guatemala', True),
(459, 'escuela las americas', True),
(460, 'escuela especial andalue', True),
(461, 'escuela basica reina de suecia', True),
(462, 'liceo alcalde gonzalo perez llona', True),
(463, 'colegio alcazar', True),
(464, 'escuela basica municipal san luis', True),
(465, 'escuela basica los bosquinos', True),
(466, 'colegio munic. san sebastian de rinconada', True),
(467, 'escuela basica municipal los alerces de', True),
(468, 'liceo nacional de maipu', True),
(469, 'escuela emaus de maipu', True),
(470, 'liceo guillermo labarca huberston', True),
(472, 'escuela platon', True),
(473, 'escuela abate molina', True),
(474, 'escuela diego portales', True),
(475, 'escuela inglaterra', True),
(476, 'escuela angelmo', True),
(477, 'escuela insigne gabriela', True),
(478, 'escuela espana', True),
(479, 'escuela lo franco', True),
(480, 'escuela antumalal', True),
(481, 'escuela calicanto', True),
(482, 'escuela menbrillar', True),
(483, 'escuela basica municipal grenoble', True),
(484, 'escuela republica de la india', True),
(485, 'escuela gil de castro', True),
(486, 'liceo industrial benjamin franklin', True),
(487, 'liceo mun. centro educacional', True),
(488, 'escuela monsenor manuel larrain', True),
(489, 'escuela teniente hernan merino correa', True),
(490, 'escuela estrella de chile', True),
(491, 'escuela estado de florida', True),
(492, 'escuela alexander graham bell', True),
(493, 'escuela el salitre', True),
(494, 'escuela alberto einstein', True),
(495, 'escuela monsenor carlos oviedo', True),
(496, 'escuela francisco ochagavia hurtado', True),
(497, 'escuela elvira santa cruz ossa', True),
(498, 'liceo de adultos alberto galleguillos j.', True),
(499, 'escuela basica melvin jones', True),
(500, 'escuela san daniel', True),
(501, 'liceo ciudad de brasilia', True),
(502, 'esc.comodoro arturo merino benitez', True),
(503, 'escuela lo boza', True),
(504, 'colegio finlandia', True),
(505, 'liceo monsenor enrique alvear', True),
(506, 'escuela puerto futuro', True),
(508, 'escuela juana de lestonac', True),
(509, 'escuela basica isabel le brun', True),
(510, 'escuela thomas alva edison', True),
(511, 'escuela domingo santa maria gonzalez', True),
(512, 'liceo municipal francisco infante abbot', True),
(513, 'escuela capitan jose luis araneda', True),
(514, 'escuela general manuel bulnes prieto', True),
(515, 'escuela rebeca matte bello', True),
(516, 'escuela general alejandro gorostiaga', True),
(517, 'escuela basica corbeta esmeralda', True),
(518, 'escuela juana atala de hirmas', True),
(519, 'esc. basica monserrat robert de garcia', True),
(520, 'escuela basica lo velasquez', True),
(521, 'escuela basica r.p. gustavo le paige', True),
(522, 'esc.munic.de parvulos hernan del sol', True),
(523, 'escuela alianza', True),
(524, 'liceo poliv. los heroes de la concepcion', True),
(525, 'escuela presidente roosevelt', True),
(526, 'escuela republica de italia', True),
(527, 'escuela republica de croacia', True),
(528, 'escuela herminda de la victoria', True),
(529, 'escuela millahue', True),
(530, 'escuela violeta parra', True),
(531, 'escuela provincia de arauco', True),
(532, 'escuela general rene escauriaza', True),
(533, 'escuela federico acevedo salazar', True),
(534, 'escuela basica paulo freire', True),
(535, 'escuela leonardo da vinci', True),
(536, 'escuela doctor treviso girardi tonelli', True),
(537, 'escuela intendente saavedra', True),
(538, 'escuela santander de espana', True),
(539, 'colegio neptuno', True),
(540, 'escuela maria luisa bombal', True),
(541, 'escuela ciudad santo domingo de guzman', True),
(542, 'escuela prof. manuel guerrero ceballos', True),
(543, 'escuela sargento candelaria', True),
(545, 'centro integrado de adultos', True),
(546, 'escuela especial sgto.cadelaria', True),
(548, 'liceo dr. luis vargas salcedo', True),
(549, 'escuela basica condores de plata', True),
(550, 'escuela lothar kommer bruger', True),
(551, 'escuela j.prieto vial', True),
(552, 'escuela estrella de chile', True),
(553, 'escuela santa adela', True),
(554, 'ejercito libertador', True),
(555, 'colegio ciudad de caracas', True),
(556, 'complejo educacional pedro prado', True),
(557, 'escuela jaime gomez garcia', True),
(558, 'escuela profesora gladys valenzuela', True),
(559, 'escuela golda meir', True),
(560, 'escuela ignacio carrera pinto', True),
(561, 'escuela mariscal de ayacucho', True),
(562, 'escuela sor teresa de los andes', True),
(563, 'escuela poeta pablo neruda', True),
(564, 'escuela republica de estados unidos', True),
(565, 'escuela basica ataturk', True),
(566, 'escuela poeta vicente huidobro', True),
(567, 'esc.de educacion diferencial quillahue', True),
(568, 'escuela centro educ.integral de adultos', True),
(569, 'escuela carlos condell de la haza', True),
(570, 'escuela arnaldo falabella', True),
(572, 'escuela republica de austria', True),
(574, 'escuela basica union latinoamericana', True),
(576, 'centro educ.munic. dr. amador nechme r.', True),
(577, 'liceo politec. guillermo feliu cruz', True),
(578, 'escuela basica republica de francia', True),
(579, 'escuela basica prof.ramon del rio', True),
(580, 'escuela basica pacto andino', True),
(581, 'escuela basica', True),
(582, 'escuela basica japon', True),
(583, 'escuela fco.garcia huidobro', True),
(584, 'escuela e-36 anexo', True),
(585, 'liceo polivalente juan a.rios depto.educ.qta.normal', True),
(586, 'escuela basica reino de noruega depto.educ.qta.normal', True),
(587, 'escuela el roto chileno', True),
(588, 'escuela presidente prieto', True),
(589, 'liceo polivalente a-119', True),
(590, 'liceo polivalente', True),
(592, 'escuela talacanta', True),
(593, 'escuela republica de grecia', True),
(594, 'liceo polivalente de -anexo', True),
(595, 'escuela manuel rodriguez erdoiza', True),
(596, 'escuela estrella de belen', True),
(597, 'escuela alborada', True),
(598, 'escuela luis undurraga', True),
(599, 'escuela el pino viejo de lonquen', True),
(600, 'escuela basica tegualda', True),
(601, 'escuela basica del poniente', True),
(603, 'centro de educacion general basica', True),
(604, 'liceo republica de italia', True),
(605, 'escuela basica efrain maldonado torres', True),
(606, 'esc.basica san antonio de naltagua', True),
(607, 'escuela rural las parcelas', True),
(608, 'escuela basica futuro las mercedes', True),
(609, 'liceo poliv. luis humberto acosta gay', True),
(610, 'escuela republica del ecuador', True),
(611, 'esc. basica e 741 javiera carrera verdugo', True),
(612, 'escuela el paico', True),
(613, 'escuela republica de honduras', True),
(614, 'escuela chinigue el cristo', True),
(615, 'escuela el ramanso', True),
(616, 'liceo municipalizado', True),
(617, 'escuela teresa de calcuta', True),
(618, 'escuela emilia lascar', True),
(619, 'escuela rosalina pescio vargas', True),
(620, 'liceo comercial republica de brasil', True),
(621, 'liceo comercial republica del brasil', True),
(622, 'escuela republica checa', True),
(623, 'escuela mand eduardo frei montalva', True),
(624, 'escuela diferencial alegria de vivir', True),
(625, 'escuela sonia plaza castro', True),
(626, 'escuela malloco', True),
(627, 'escuela republica de israel', True),
(628, 'escuela pelvin san francisco de asis', True),
(629, 'escuela dolores cattin faundez', True),
(631, 'liceo poliv. hnos. sotomayor baeza', True),
(633, 'escuela ignacio serrano montaner', True),
(634, 'liceo gabriela mistral de', True),
(635, 'colegio huilco alto', True),
(636, 'colegio mons. jaime larrain bunster', True),
(638, 'escuela san jose de la villa', True),
(639, 'escuela gral. carol urzua', True),
(640, 'escuela republica del brasil', True),
(641, 'colegio pomaire', True),
(643, 'liceo poliv. el bollenar', True),
(644, 'escuela santa rosa esmeralda', True),
(645, 'escuela claudio arrau', True),
(646, 'escuela patricio larrain gandarillas', True),
(647, 'escuela pedro marin alemany', True),
(648, 'escuela basica carmen bajo', True),
(649, 'escuela ramon noguera prieto', True),
(650, 'escuela cholqui', True),
(651, 'escuela san diego', True),
(652, 'escuela puangue', True),
(653, 'escuela lidia matte hurtado', True),
(654, 'escuela el transito', True),
(655, 'escuela jose camarena escriva', True),
(656, 'escuela huechun', True),
(657, 'escuela tantehue', True),
(658, 'escuela raquel fernandez de morande', True),
(659, 'escuela padre alberto hurtado', True),
(660, 'escuela basica el pabellon', True),
(661, 'colegio los jazmines', True),
(662, 'escuela chorombo alto', True),
(663, 'escuela los rulos', True),
(664, 'escuela chorombo bajo', True),
(665, 'escuela las mercedes', True),
(666, 'escuela santa emilia', True),
(667, 'escuela ibacache', True),
(671, 'escuela loica arriba', True),
(672, 'escuela loica abajo', True),
(673, 'escuela el prado', True),
(674, 'escuela llancay', True),
(675, 'escuela nihue bajo', True),
(676, 'escuela enrique reymond aldunate', True),
(677, 'escuela de quelentaro alto', True),
(678, 'escuela lo encanado', True),
(679, 'escuela corneche', True),
(680, 'escuela la manga', True),
(681, 'escuela sta. rosa lotesore', True),
(682, 'escuela fundo cabimbao', True),
(683, 'liceo municipal sara troncoso troncoso', True),
(684, 'escuela el asiento', True),
(685, 'escuela barrancas de pechy', True),
(686, 'escuela san alfonso', True),
(687, 'escuela hacienda', True),
(688, 'escuela basica valle de puangue', True),
(690, 'escuela san jose obrero', True),
(691, 'liceo presidente balmaceda', True),
(692, 'escuela fernando carvajal pinto', True),
(693, 'escuela eliecer perez vargas', True),
(694, 'escuela heriberto erlwein s.', True),
(695, 'escuela bas. munic. cuyuncavi', True),
(696, 'liceo paul harris', True),
(697, 'escuela republica argentina', True),
(698, 'escuela cristal chile', True),
(699, 'escuela la esperanza', True),
(700, 'escuela camino de luz', True),
(701, 'escuela consolidada', True),
(702, 'liceo ind. municipalizado a n_ 116', True),
(703, 'liceo san geronimo', True),
(704, 'escuela maipo', True),
(706, 'escuela villa', True),
(707, 'escuela republica de grecia', True),
(708, 'centro de educ.integral nueva esperanza', True),
(709, 'escuela los andes', True),
(710, 'escuela nonato coo', True),
(711, 'escuela villa', True),
(712, 'escuela ejercito libertador', True),
(713, 'escuela los pimientos', True),
(714, 'escuela manuel plaza', True),
(715, 'liceo munic.ing.militar juan mackena o.', True),
(716, 'escuela casas viejas', True),
(717, 'escuela oscar bonilla', True),
(718, 'escuela luis matte larrain', True),
(719, 'escuela gabriela', True),
(720, 'escuela las palmas', True),
(721, 'escuela especial open door', True),
(722, 'liceo municipal chiloe', True),
(723, 'escuela andes del sur', True),
(724, 'escuela basica padre alberto hurtado', True),
(725, 'escuela volcan san jose', True),
(726, 'escuela de parvulos municipal altue', True),
(727, 'c. integral de ad. profesora teresa moya reye', True),
(728, 'liceo munic. tec. prof. el llano', True),
(729, 'escuela santa rita', True),
(730, 'escuela lo arcaya', True),
(731, 'liceo el principal', True),
(732, 'escuela san juan', True),
(733, 'escuela la puntilla', True),
(734, 'liceo polivalente', True),
(735, 'escuela julieta becerra alvarez', True),
(736, 'escuela el canelo', True),
(737, 'escuela el melocoton', True),
(738, 'escuela de concentracion fronteriza', True),
(739, 'escuela fronteriza', True),
(740, 'escuela la obra', True),
(741, 'escuela bas.y esp. integradora el manzano', True),
(742, 'escuela 636 san alfonso', True),
(743, 'escuela basica las melosas', True),
(744, 'centro educacional mun.mariano latorre', True),
(745, 'liceo n523', True),
(746, 'escuela capitan avalos', True),
(747, 'escuela pablo de rokha', True),
(748, 'escuela municipal violeta parra', True),
(749, 'colegio neruda', True),
(750, 'liceo villa la pintana', True),
(751, 'liceo municipalizado cent.ed.', True),
(752, 'liceo victor jara', True),
(753, 'escuela basica juan de dios aldea', True),
(754, 'liceo municipalizado marcelo astoreca c.', True),
(755, 'liceo municipal el roble', True),
(756, 'esc.basica prof.aurelia rojas burgos', True),
(757, 'liceo de adultos ceia de la pintana', True),
(758, 'liceo benjamin vicuna mackenna', True),
(759, 'escuela gaurdiamarina ernesto riquelme', True),
(760, 'escuela bellavista', True),
(761, 'escuela elsa santibanez', True),
(762, 'escuela marcela paz', True),
(763, 'escuela republica dominicana', True),
(764, 'liceo nuevo amanecer', True),
(765, 'escuela las araucarias', True),
(766, 'escuela sotero del rio', True),
(767, 'escuela areas verdes', True),
(768, 'complejo educ. municipal carden.a.samore', True),
(769, 'liceo polivalente los almendros', True),
(770, 'liceo andres bello', True),
(771, 'escuela jose alvo abvuaf', True),
(772, 'escuela las lilas', True),
(773, 'escuela cataluna', True),
(774, 'liceo indira gandhi', True),
(775, 'escuela santa irene', True),
(776, 'escuela lo canas', True),
(777, 'escuela villas unidas', True),
(778, 'escuela los cerezos', True),
(779, 'escuela los quillayes', True),
(780, 'escuela oscar castro', True),
(781, 'colegio capitan pastene', True),
(782, 'escuela anexo lo canas', True),
(783, 'escuela de parvulos samorito', True),
(784, 'colegio capitan pastene anexo', True),
(785, 'colegio maria elena', True),
(786, 'profesor francisco vergara bobadilla', True),
(788, 'liceo rebeca olivares benitez', True),
(789, 'liceo polivalente rigoberto fontt i.', True),
(790, 'escuela basica marcos gooycolea cortes', True),
(791, 'escuela basica santa teresa del carmelo', True),
(792, 'escuela especial ernesto soto negrete', True),
(793, 'escuela premio nobel pablo neruda', True),
(794, 'escuela basica base aerea', True),
(795, 'liceo esmeralda', True),
(796, 'escuela basica algarrobal', True),
(797, 'esc.basica coronel enrique cabrera', True),
(798, 'esc.basica francisco petrinovic karlovac', True),
(799, 'escuela basica san vicente de lo arcaya', True),
(800, 'escuela basica santa marta de liray', True),
(801, 'escuela san francisco de asis', True),
(802, 'liceo rebeca olivares b.', True),
(803, 'centro educativo la puerta', True),
(804, 'colegio municipal instituto chacabuco', True),
(805, 'esc. especial elsa matilde ulrich jara', True),
(806, 'escuela lipangue', True),
(808, 'escuela manuel segovia montenegro', True),
(809, 'escuela republica de polonia', True),
(810, 'escuela basica cacique colin', True),
(811, 'escuela santa barbara', True),
(812, 'escuela polonia gutierrez c.', True),
(813, 'escuela santa rosa de', True),
(814, 'escuela santa sara', True),
(815, 'escuela el lucero', True),
(816, 'escuela sol de septiembre', True),
(817, 'liceo municip. de adultos pedro j. rodriguez', True),
(818, 'liceo municipal de batuco', True),
(819, 'liceo polivalente manuel rodriguez', True),
(820, 'liceo huertos familiares', True),
(821, 'escuela rungue', True),
(822, 'escuela santa matilde', True),
(823, 'escuela huechun', True),
(824, 'escuela capilla de caleu', True),
(825, 'escuela el llano de caleu', True),
(826, 'escuela basica montenegro', True),
(827, 'escuela plazuela de polpaico', True),
(828, 'liceo gabriela mistral', True),
(829, 'liceo rosa ester alesandri rodriguez', True),
(830, 'escuela basica cornelia olivares', True),
(831, 'escuela de parvulos antu-huilen', True),
(832, 'liceo san francisco de quito', True),
(833, 'escuela nueva zelandia', True),
(834, 'escuela basica camilo mori', True),
(835, 'escuela basica cd.arturo merino benitez', True),
(836, 'escuela diferencial f-82', True),
(837, 'liceo presidente balmaceda', True),
(838, 'escuela luis galdames', True),
(839, 'liceo valentin letelier', True),
(840, 'liceo paula jaraquemada', True),
(841, 'esc.bas.bilingue republica del paraguay', True),
(842, 'escuela republica del paraguay', True),
(843, 'escuela de adultos jorge alessandri r.', True),
(844, 'escuela basica dr juan verdaguer planas', True),
(845, 'liceo arturo perez canto', True),
(846, 'centro educacional jose miguel carrera', True),
(847, 'complejo educ. juanita fernandez s.', True),
(848, 'escuela sargento 2. daniel rebolledo', True),
(849, 'escuela espana', True),
(850, 'escuela escritora marcela paz', True),
(851, 'escuela puerto rico', True),
(852, 'centro educ.escritores de chile', True),
(853, 'escuela victor cuccuini', True),
(854, 'escuela marta colvin', True),
(855, 'escuela anne eleonor roosevelt', True),
(856, 'escuela mun.hermana maria goretti', True),
(857, 'escuela rafael valdivieso', True),
(858, 'escuela educ.dif. sta. teresa de avila', True),
(859, 'centro educ. ministro diego portales', True),
(861, 'escuela basica carlos prats g.', True),
(862, 'escuela basica copenhague', True),
(863, 'escuela adelaida la fetra', True),
(864, 'escuela e-128', True),
(865, 'escuela santa victoria', True),
(866, 'escuela las canteras', True),
(867, 'escuela de guayaquil', True),
(868, 'escuela estado de michigan', True),
(869, 'escuela luis cruz martinez', True),
(870, 'escuela basica el manio', True),
(871, 'escuela basic.soldado heroe miguel prado', True),
(872, 'complejo educacional j. miguel carrera', True),
(873, 'esc. bas.municipal mercedes fontecilla', True),
(874, 'escuela profesora maria luisa sepulveda', True),
(875, 'liceo alcalde jorge indo', True),
(876, 'escuela municipal valle de luna', True),
(877, 'liceo de adultos poeta vicente huidobro', True),
(878, 'escuela basica ana frank', True),
(879, 'escuela b-sica pucara lasana', True),
(880, 'liceo poeta federico garcia lorca', True),
(881, 'liceo abdon cifuentes', True),
(882, 'liceo poliv. abdon cifuentes', True),
(883, 'liceo agustin edwards', True),
(884, 'escuela unesco', True),
(885, 'escuela d-114', True),
(886, 'escuela sol naciente', True),
(887, 'escuela horacio johnson gana', True),
(888, 'escuela dra.eloisa diaz insunza', True),
(889, 'liceo munc.almirante galvarino riveros', True),
(890, 'escuela araucarias de chile', True),
(891, 'escuela valle del inca', True),
(892, 'escuela conchali', True),
(893, 'escuela allipen', True),
(894, 'centro educ. poeta eusebio lillo', True),
(895, 'escuela atenea', True),
(896, 'escuela aviador dagoberto godoy f.', True),
(897, 'escuela basica likan-antai', True),
(898, 'escuela esp. humberto aranda irribarren', True),
(899, 'escuela camilo henriquez', True),
(900, 'liceo municipal santa maria de conchali', True),
(901, 'liceo politecnico chilean eagles', True),
(902, 'colegio san pedro nolasco de quillota', True),
(907, 'Shirayuri', True);

--rubros--
INSERT INTO "MP_rubro"(
            id, nombre)
    VALUES 
    (9, 'irrigaciones'),
(14, 'repelentes de insectos'),
(18, 'chimeneas'),
(20, 'molinos'),
(23, 'productos quÃ­micos'),
(42, 'agricultura'),
(43, 'equipo para protecciÃ³n personal'),
(54, 'regalos promocionales'),
(56, 'cristalerÃ­as'),
(58, 'vajillas'),
(60, 'ambientadores'),
(65, 'musica, vÃ­deo y jugueterÃ­a'),
(66, 'arte'),
(68, 'clases de baile'),
(70, 'turismo'),
(73, 'recreaciÃ³n infantil'),
(77, 'flores y plantas'),
(81, 'idiomas'),
(87, 'parques acuÃ¡ticos'),
(111, 'organizaciones de eventos'),
(112, 'mantenimiento negocio de hostelerÃ­a'),
(113, 'suministros hotelera/ amenities'),
(117, 'revistas'),
(128, 'centros de estÃ©ticas'),
(134, 'equipos para estÃ©tica'),
(135, 'servicios de peluquerÃ­a'),
(141, 'ambientadores'),
(143, 'alimentaciÃ³n general'),
(144, 'bebidas'),
(152, 'envasado y embalaje de alimentos'),
(164, 'etiquetas para textil'),
(165, 'prendas de protecciÃ³n laboral'),
(166, 'accesorios para la industrial textil'),
(170, 'maletas y equipajes'),
(172, 'bolsas de tela'),
(174, 'software'),
(177, 'telefonÃ­a'),
(178, 'domestica'),
(180, 'gestiÃ³n de proyectos'),
(184, 'adaptaciÃ³n lopd'),
(186, 'energÃ­a'),
(188, 'servicios multimedia'),
(195, 'consultorÃ­a informÃ¡tica'),
(196, 'transportes'),
(201, 'call center/ atenciÃ³n telefÃ³nica'),
(206, 'servicio de desinfecciÃ³n y fumigaciÃ³n'),
(214, 'servicio de secretariado'),
(222, 'accesorios corporativos'),
(223, 'mediciones'),
(224, 'organizaciÃ³n de eventos'),
(236, 'compra/ venta de empresas'),
(245, 'alquiler locales y despachos'),
(249, 'diseÃ±o de planos y maquetas'),
(253, 'consultorÃ­as en arquitectura'),
(254, 'trabajos verticales');


--Habilidades--
INSERT INTO "MP_tipohabilidad"(
            id, nombre)
VALUES (1, 'Deporte'),(2,'Idioma'),(3,'Computación');

--Deporte--
INSERT INTO "MP_habilidad"(
            id, nombre, "tipoHabilidad_id")
    VALUES 
(1, 'Ala delta ',1),
(2, 'Acrobacia ',1),
(3, 'Acuatlon ',1),
(4, 'Aerobic ',1),
(5, 'Aikido ',1),
(6, 'Ajedrez ',1),
(7, 'Alpinismo ',1),
(8, 'Artes marciales ',1),
(9, 'Atletismo ',1),
(10, 'Automobilismo ',1),
(11, 'Baloncesto ',1),
(12, 'Balonmano ',1),
(13, 'Billar ',1),
(17, 'Bodyboard ',1),
(18, 'Boxeo ',1),
(19, 'Badminton ',1),
(20, 'Beisbol ',1),
(21, 'Caza ',1),
(22, 'Ciclismo ',1),
(25, 'Criquet ',1),
(27, 'Cuadratlon ',1),
(28, 'Curling ',1),
(29, 'Danza deportiva ',1),
(30, 'Dardos ',1),
(31, 'Futbol ',1),
(32, 'Futbol playa ',1),
(33, 'Futbol sala ',1),
(34, 'Golf ',1),
(35, 'Gimnasia ',1),
(36, 'Gimnasia ritmica ',1),
(37, 'Halterofilia ',1),
(38, 'Hipica ',1),
(39, 'Hockey en patines ',1),
(40, 'Hockey sobre hierba ',1),
(41, 'Hockey sobre hielo ',1),
(42, 'Hockey ',1),
(43, 'Hurling ',1),
(44, 'Jiu-Jitsu ',1),
(45, 'Judo ',1),
(46, 'Karate ',1),
(47, 'Kendo ',1),
(48, 'Kickboxing ',1),
(49, 'Karting ',1),
(50, 'Kung Fu ',1),
(51, 'Lacrosse ',1),
(52, 'Lucha ',1),
(53, 'Lucha tradicional',1),
(56, 'Motociclismo ',1),
(57, 'Motonautica ',1),
(58, 'Mhuai Thay ',1),
(59, 'Natacion ',1),
(62, 'Paracaismo ',1),
(63, 'Parapente ',1),
(64, 'Parkour ',1),
(65, 'Patinaje ',1),
(66, 'Paintball ',1),
(67, 'Pelota ',1),
(68, 'Pelota valenciana ',1),
(69, 'Pelota vasca ',1),
(70, 'Pentatlon moderno ',1),
(71, 'Pesca deportiva ',1),
(74, 'Polo ',1),
(75, 'Remo ',1),
(76, 'Rugby ',1),
(77, 'Salto de trampolin ',1),
(78, 'Senderismo ',1),
(79, 'Softbol ',1),
(81, 'Skateboard ',1),
(83, 'Snowboard ',1),
(84, 'Speedball ',1),
(85, 'Squash ',1),
(86, 'Sumo ',1),
(88, 'Surf ',1),
(89, 'Tenis ',1),
(90, 'Tenis de mesa ',1),
(91, 'Tiro ',1),
(92, 'Tiro con arco ',1),
(93, 'Triatlon ',1),
(94, 'Taekwondo ',1),
(96, 'Vela ',1),
(97, 'Voleibol ',1),
(98, 'Volei playa ',1),
(99, 'Valetodo ',1),
(100, 'Waterpolo ',1),
(101, 'Windsurf ',1),
(102, 'Wushu ',1),
(103, 'Win Tsun ',1),
(105, 'Gimnasia ',1),
(106, 'Gimnasia ritmica ',1),
(107, 'Esgrima ',1),
(108, 'Espeleoloxia ',1),
(109, 'Esqui ',1),
(110, 'Equitacion ',1);

--Idiomas--
INSERT INTO "MP_habilidad"(
            id, nombre, "tipoHabilidad_id")
    VALUES 
(111, 'Afrikaans',2),
(112, 'Albanés',2),
(113, 'Alemán',2),
(114, 'Amharico',2),
(115, 'Arabe',2),
(116, 'Armenio',2),
(117, 'Bengali',2),
(118, 'Bieloruso',2),
(119, 'Birmanés',2),
(120, 'Bulgaro',2),
(121, 'Catalan',2),
(122, 'Checo',2),
(123, 'Chino',2),
(124, 'Coreano',2),
(125, 'Croata',2),
(126, 'Danés',2),
(127, 'Dari',2),
(128, 'Dzongkha',2),
(129, 'Escocés',2),
(130, 'Eslovaco',2),
(131, 'Esloveniano',2),
(132, 'Español',2),
(133, 'Esperanto',2),
(134, 'Estoniano',2),
(135, 'Faroese',2),
(136, 'Farsi',2),
(137, 'Finlandés',2),
(138, 'Francés',2),
(139, 'Gaelico',2),
(140, 'Galese',2),
(141, 'Gallego',2),
(142, 'Griego',2),
(143, 'Hebreo',2),
(144, 'Hindi',2),
(145, 'Holandés',2),
(146, 'Hungaro',2),
(147, 'Inglés',2),
(148, 'Indonesio',2),
(149, 'Inuktitut(Eskimo)',2),
(150, 'Islandico',2),
(151, 'Italiano',2),
(152, 'Japonés',2),
(153, 'Khmer',2),
(154, 'Kurdo',2),
(155, 'Lao',2),
(156, 'Laponico',2),
(157, 'Latviano',2),
(158, 'Lituano',2),
(159, 'Macedonio',2),
(160, 'Malayés',2),
(161, 'Maltés',2),
(162, 'Nepali',2),
(163, 'Noruego',2),
(164, 'Pashto',2),
(165, 'Polaco',2),
(166, 'Portugúes',2),
(167, 'Rumano',2),
(168, 'Ruso',2),
(169, 'Serbio',2),
(170, 'Somali',2),
(171, 'Suahili',2),
(172, 'Sueco',2),
(173, 'Tagalog-Filipino',2),
(174, 'Tajik',2),
(175, 'Tamil',2),
(176, 'Tailandés',2),
(177, 'Tibetano',2),
(178, 'Tigrinia',2),
(179, 'Tonganés',2),
(180, 'Turco',2),
(181, 'Turkmenistano',2),
(182, 'Ucraniano',2),
(183, 'Urdu',2),
(184, 'Uzbekistano',2),
(185, 'Vasco',2),
(186, 'Vietnamés',2);
