from django.contrib import admin
from MP.models import *

admin.site.register(Socio)
admin.site.register(Nacionalidad)
admin.site.register(RegistroPago)
admin.site.register(Mensaje)
admin.site.register(TipoHabilidad)
admin.site.register(Habilidad)
admin.site.register(OtrasHabilidades)
admin.site.register(Rubro)
admin.site.register(Cargo)
admin.site.register(EmpleoBuscado)
admin.site.register(ExperienciaLaboral)
admin.site.register(Titulo)
admin.site.register(Institucion)
admin.site.register(Estudios)
admin.site.register(TitulosEnInstituciones)
admin.site.register(Localidad)
admin.site.register(LocalidadConSocio)